package uz.alvasti.lotinkirill.wordtranslator;

public class SubWordLibrary implements Translate{

    @Override
    public String translateToLatin(String word) {


        for (String[] strings : subWordsCyrillicInitial) {
            String cyrillic = strings[0];
            String latin = strings[1];
            word = word.replaceAll(cyrillic, latin);
        }
        return word;
    }

    @Override
    public String translateToCyrillic(String word) {
        for (String[] strings : subWordsLatinInitial) {
            String latin = strings[0];
            String cyrillic = strings[1];
            word = word.replaceAll(latin, cyrillic);
        }
        return word;
    }

    private final String[][] subWordsLatinInitial = {
            {"o‘jaz", "ўъжаз"},
            {"O‘JAZ", "ЎЪЖАЗ"},
            {"o‘jiza", "ўъжиза"},
            {"O‘JIZA", "ЎЪЖИЗА"},
            {"o‘tabar", "ўътабар"},
            {"O‘TABAR", "ЎЪТАБАР"},
            {"o‘tadil", "ўътадил"},
            {"O‘TADIL", "ЎЪТАДИЛ"},
            {"aye", "ае"},
            {"ayE", "аЕ"},
            {"aYe", "аЕ"},
            {"aYE", "аЕ"},
            {"Aye", "Ае"},
            {"AYe", "АЕ"},
            {"AyE", "АЕ"},
            {"AYE", "АЕ"},
            {"iye", "ие"},
            {"iYe", "ие"},
            {"iyE", "иЕ"},
            {"iYE", "иЕ"},
            {"Iye", "Ие"},
            {"IYe", "Ие"},
            {"IyE", "ИЕ"},
            {"IYE", "ИЕ"},
            {"eye", "ее"},
            {"EYE", "ЕЕ"},
            {"ye", "е"},
            {"YE", "Е"},
            {"sh","ш"},
            {"SH","Ш"},
            {"yu", "ю"},
            {"YU", "Ю"},
            {"ya", "я"},
            {"YA", "Я"},
            {"yo", "ё"},
            {"YO", "Ё"},
            {"yo‘", "йў"},
            {"Yo‘", "Йў"},
            {"YO‘", "ЙЎ"},
            {"yoye", "ёе"},
            {"YOYE", "ЁЕ"},
            {"oye", "ое"},
            {"OYE", "ОЕ"},
            {"uye", "уе"},
            {"UYE", "УЕ"},
            {"o‘ye", "ўе"},
            {"O‘YE", "ЎЕ"},
            {"yuye", "юе"},
            {"YUYE", "ЮЕ"},
            {"yaye", "яе"},
            {"YAYE", "ЯЕ"},
            {"tss", "цц"},
            {"TSS", "ЦЦ"},
            {"bsiya", "бция"},
            {"BSIYA", "БЦИЯ"},
            {"bsion", "бцион"},
            {"BSION", "БЦИОН"},
            {"ksiya", "кция"},
            {"KSIYA", "КЦИЯ"},
            {"ksion", "кцион"},
            {"KSION", "КЦИОН"},
            {"nsiya", "нция"},
            {"NSIYA", "НЦИЯ"},
            {"nsion", "нцион"},
            {"NSION", "НЦИОН"},
            {"rsiya", "рция"},
            {"RSIYA", "РЦИЯ"},
            {"rsion", "рцион"},
            {"RSION", "РЦИОН"},
            {"psiya", "пция"},
            {"PSIYA", "ПЦИЯ"},
            {"psion", "пцион"},
            {"PSION", "ПЦИОН"},
            {"tsiya", "ция"},
            {"TSIYA", "ЦИЯ"},
            {"tsist", "цист"},
            {"TSIST", "ЦИСТ"},
            {"tsizm", "цизм"},
            {"TSIZM", "ЦИЗМ"},
            {"tsit", "цит"},
            {"TSIT", "ЦИТ"},
            {"tsevt", "цевт"},
            {"TSEVT", "ЦЕВТ"},
            {"tsept", "цепт"},
            {"TSEPT", "ЦЕПТ"},
            {"tser", "цер"},
            {"TSER", "ЦЕР"},
            {"tsia", "циа"},
            {"TSIA", "ЦИА"},
            {"sia", "циа"},
            {"SIA", "ЦИА"},
            {"tsikl", "цикл"},
            {"TSIKL", "ЦИКЛ"},
            {"tsio", "цио"},
            {"TSIO", "ЦИО"},
            {"tsiu", "циу"},
            {"TSIU", "ЦИУ"},
            {"siu", "циу"},
            {"SIU", "ЦИУ"},
            {"SʼH", "СҲ"},
            {"Sʼh", "Сҳ"},
            {"sʼh", "сҳ"},
            {"syom", "съём"},
            {"SYOM", "СЪЁМ"}
    };

    public final String[][] subWordsCyrillicInitial = {
            {"ўъжаз", "o‘jaz"},
            {"ЎЪЖАЗ", "O‘JAZ"},
            {"ўъжиза", "o‘jiza"},
            {"ЎЪЖИЗА", "O‘JIZA"},
            {"ўътабар", "o‘tabar"},
            {"ЎЪТАБАР", "O‘TABAR"},
            {"ўътадил", "o‘tadil"},
            {"ЎЪТАДИЛ", "O‘TADIL"},
            {"ае", "aye"},
            {"аЕ", "ayE"},
            {"аЕ", "aYe"},
            {"аЕ", "aYE"},
            {"Ае", "Aye"},
            {"АЕ", "AYe"},
            {"АЕ", "AyE"},
            {"АЕ", "AYE"},
            {"ие", "iye"},
            {"ие", "iYe"},
            {"иЕ", "iyE"},
            {"иЕ", "iYE"},
            {"Ие", "Iye"},
            {"Ие", "IYe"},
            {"ИЕ", "IyE"},
            {"ИЕ", "IYE"},
            {"ее", "eye"},
            {"ЕЕ", "EYE"},
            {"е", "ye"},
            {"Е", "YE"},
            {"ш", "sh"},
            {"Ш", "SH"},
            {"ю", "yu"},
            {"Ю", "YU"},
            {"я", "ya"},
            {"Я", "YA"},
            {"ё", "yo"},
            {"Ё", "YO"},
            {"йў", "yo‘"},
            {"Йў", "Yo‘"},
            {"ЙЎ", "YO‘"},
            {"ёе", "yoye"},
            {"ЁЕ", "YOYE"},
            {"ое", "oye"},
            {"ОЕ", "OYE"},
            {"уе", "uye"},
            {"УЕ", "UYE"},
            {"ўе", "o‘ye"},
            {"ЎЕ", "O‘YE"},
            {"юе", "yuye"},
            {"ЮЕ", "YUYE"},
            {"яе", "yaye"},
            {"ЯЕ", "YAYE"},
            {"бц", "bs"},
            {"БЦ", "BS"},
            {"вц", "vs"},
            {"ВЦ", "VS"},
            {"гц", "gs"},
            {"ГЦ", "GS"},
            {"дц", "ds"},
            {"ДЦ", "DS"},
            {"жц", "js"},
            {"ЖЦ", "JS"},
            {"зц", "zs"},
            {"ЗЦ", "ZS"},
            {"йц", "ys"},
            {"ЙЦ", "YS"},
            {"кц", "ks"},
            {"КЦ", "KS"},
            {"лц", "ls"},
            {"ЛЦ", "LS"},
            {"мц", "ms"},
            {"МЦ", "MS"},
            {"нц", "ns"},
            {"НЦ", "NS"},
            {"пц", "ps"},
            {"ПЦ", "PS"},
            {"рц", "rs"},
            {"РЦ", "RS"},
            {"Сц", "Ss"},
            {"сц", "ss"},
            {"сЦ", "sS"},
            {"СЦ", "SS"},
            {"тц", "ts"},
            {"ТЦ", "TS"},
            {"фц", "fs"},
            {"ФЦ", "FS"},
            {"хц", "xs"},
            {"ХЦ", "XS"},
            {"цц", "tss"},
            {"ЦЦ", "TSS"},
            {"чц", "chs"},
            {"ЧЦ", "CHS"},
            {"шц", "shs"},
            {"ШЦ", "SHS"},
            {"бция", "bsiya"},
            {"БЦИЯ", "BSIYA"},
            {"бцион", "bsion"},
            {"БЦИОН", "BSION"},
            {"кция", "ksiya"},
            {"КЦИЯ", "KSIYA"},
            {"кцион", "ksion"},
            {"КЦИОН", "KSION"},
            {"нция", "nsiya"},
            {"НЦИЯ", "NSIYA"},
            {"нцион", "nsion"},
            {"НЦИОН", "NSION"},
            {"рция", "rsiya"},
            {"РЦИЯ", "RSIYA"},
            {"рцион", "rsion"},
            {"РЦИОН", "RSION"},
            {"пция", "psiya"},
            {"ПЦИЯ", "PSIYA"},
            {"пцион", "psion"},
            {"ПЦИОН", "PSION"},
            {"ция", "tsiya"},
            {"ЦИЯ", "TSIYA"},
            {"цист", "tsist"},
            {"ЦИСТ", "TSIST"},
            {"цизм", "tsizm"},
            {"ЦИЗМ", "TSIZM"},
            {"цит", "tsit"},
            {"ЦИТ", "TSIT"},
            {"цевт", "tsevt"},
            {"ЦЕВТ", "TSEVT"},
            {"цепт", "tsept"},
            {"ЦЕПТ", "TSEPT"},
            {"цер", "tser"},
            {"ЦЕР", "TSER"},
            {"циа", "tsia"},
            {"ЦИА", "TSIA"},
            {"циа", "sia"},
            {"ЦИА", "SIA"},
            {"цикл", "tsikl"},
            {"ЦИКЛ", "TSIKL"},
            {"цио", "tsio"},
            {"ЦИО", "TSIO"},
            {"циу", "tsiu"},
            {"ЦИУ", "TSIU"},
            {"циу", "siu"},
            {"ЦИУ", "SIU"},
            {"СҲ", "SʼH"},
            {"Сҳ", "Sʼh"},
            {"сҳ", "sʼh"},
            {"съём", "syom"},
            {"СЪЁМ", "SYOM"},
            {"ЪЮ", "YU"},
            {"ъю", "yu"},
            {"ЬО", "YO"},
            {"ьо", "yo"},
            {"ЬЕ", "YE"},
            {"ье", "ye"},
            {"ЬЁ", "YO"},
            {"ьё", "yo"},
            {"ЪЕ", "YE"},
            {"ъе", "ye"},
            {"ЪЁ", "YO"},
            {"ъё", "yo"}
    };


//    "ц"  ts
//{" е", " ye"},
    //"ъ" "’" "ъ"
    //"ь" ""
    //q,g', x, h, o', yo, yu, ya, Ь,
}
