package uz.alvasti.lotinkirill.wordtranslator;

public class SubWordLibrary implements Translate{

    @Override
    public String translateToLatin(String word) {


        for (String[] strings : subWordsCyrillicInitial) {
            String cyrillic = strings[0];
            String latin = strings[1];
            word = word.replaceAll(cyrillic, latin);
        }
        return word;
    }

    @Override
    public String translateToCyrillic(String word) {
        for (String[] strings : subWordsLatinInitial) {
            String latin = strings[0];
            String cyrillic = strings[1];
            word = word.replaceAll(latin, cyrillic);
        }
        return word;
    }

    private final String[][] subWordsLatinInitial = {
            {"o'jaz", "ўъжаз"},
            {"o‘jiza", "ўъжиза"},
            {"o‘tabar", "ўътабар"},
            {"o‘tadil", "ўътадил"},
            {"aye", "ае"},
            {"Iye", "Ие"},
            {"iye", "ие"},
            {"eye", "ее"},
            {"yoye", "ёе"},
            {"oye", "ое"},
            {"uye", "уе"},
            {"o‘ye", "ўе"},
            {"yuye", "юе"},
            {"yaye", "яе"},
            {"AYE", "АЕ"},
            {"IYE", "ИЕ"},
            {"Aye", "Ае"},
            {"OYE", "ОЕ"},
            {"UYE", "УЕ"},
            {"O‘YE", "ЎЕ"},
            {"YUYE", "ЮЕ"},
            {"YAYE", "ЯЕ"},
            {"bs", "бц"},
            {"vs", "вц"},
            {"gs", "гц"},
            {"ds", "дц"},
            {"js", "жц"},
            {"zs", "зц"},
            {"ys", "йц"},
            {"ks", "кц"},
            {"ls", "лц"},
            {"ms", "мц"},
            {"ns", "нц"},
            {"ps", "пц"},
            {"rs", "рц"},
            {"Ss", "Сц"},
            {"ss", "сц"},
            {"ts", "тц"},
            {"fs", "фц"},
            {"xs", "хц"},
            {"tss", "цц"},
            {"chs", "чц"},
            {"shs", "шц"},
            {"bsiya", "бция"},
            {"bsion", "бцион"},
            {"ksiya", "кция"},
            {"ksion", "кцион"},
            {"nsiya", "нция"},
            {"nsion", "нцион"},
            {"rsiya", "рция"},
            {"rsion", "рцион"},
            {"psiya", "пция"},
            {"psion", "пцион"},
            {"tsiya", "ция"},
            {"tsist", "цист"},
            {"tsizm", "цизм"},
            {"tsit", "цит"},
            {"tsevt", "цевт"},
            {"tsept", "цепт"},
            {"tser", "цер"},
            {"tsia", "циа"},
            {"sia", "циа"},
            {"tsikl", "цикл"},
            {"tsio", "цио"},
            {"tsiu", "циу"},
            {"siu", "циу"},
            {"BSIYA", "БЦИЯ"},
            {"BSION", "БЦИОН"},
            {"KSIYA", "КЦИЯ"},
            {"KSION", "КЦИОН"},
            {"NSIYA", "НЦИЯ"},
            {"NSION", "НЦИОН"},
            {"RSIYA", "РЦИЯ"},
            {"RSION", "РЦИОН"},
            {"PSIYA", "ПЦИЯ"},
            {"PSION", "ПЦИОН"},
            {"TSIYA", "ЦИЯ"},
            {"TSIST", "ЦИСТ"},
            {"TSIZM", "ЦИЗМ"},
            {"TSIT", "ЦИТ"},
            {"TSEVT", "ЦЕВТ"},
            {"TSEPT", "ЦЕПТ"},
            {"TSER", "ЦЕР"},
            {"TSIA", "ЦИА"},
            {"SIA", "ЦИА"},
            {"TSIKL", "ЦИКЛ"},
            {"TSIO", "ЦИО"},
            {"TSIU", "ЦИУ"},
            {"SIU", "ЦИУ"}
    };

    public final String[][] subWordsCyrillicInitial = {
            {"ўъжаз", "o'jaz"},
            {"ўъжиза", "o‘jiza"},
            {"ўътабар", "o‘tabar"},
            {"ўътадил", "o‘tadil"},
            {"ае", "aye"},
            {"Ие", "Iye"},
            {"ие", "iye"},
            {"ее", "eye"},
            {"ёе", "yoye"},
            {"ое", "oye"},
            {"уе", "uye"},
            {"ўе", "o‘ye"},
            {"юе", "yuye"},
            {"яе", "yaye"},
            {"АЕ", "AYE"},
            {"ИЕ", "IYE"},
            {"Ае", "Aye"},
            {"ОЕ", "OYE"},
            {"УЕ", "UYE"},
            {"ЎЕ", "O‘YE"},
            {"ЮЕ", "YUYE"},
            {"ЯЕ", "YAYE"},
            {"бц", "bs"},
            {"вц", "vs"},
            {"гц", "gs"},
            {"дц", "ds"},
            {"жц", "js"},
            {"зц", "zs"},
            {"йц", "ys"},
            {"кц", "ks"},
            {"лц", "ls"},
            {"мц", "ms"},
            {"нц", "ns"},
            {"пц", "ps"},
            {"рц", "rs"},
            {"Сц", "Ss"},
            {"сц", "ss"},
            {"тц", "ts"},
            {"фц", "fs"},
            {"хц", "xs"},
            {"цц", "tss"},
            {"чц", "chs"},
            {"шц", "shs"},
            {"ьц", "s"},
            {"бция", "bsiya"},
            {"бцион", "bsion"},
            {"кция", "ksiya"},
            {"кцион", "ksion"},
            {"нция", "nsiya"},
            {"нцион", "nsion"},
            {"рция", "rsiya"},
            {"рцион", "rsion"},
            {"пция", "psiya"},
            {"пцион", "psion"},
            {"ция", "tsiya"},
            {"цист", "tsist"},
            {"цизм", "tsizm"},
            {"цит", "tsit"},
            {"цевт", "tsevt"},
            {"цепт", "tsept"},
            {"цер", "tser"},
            {"циа", "tsia"},
            {"циа", "sia"},
            {"цикл", "tsikl"},
            {"цио", "tsio"},
            {"циу", "tsiu"},
            {"циу", "siu"},
            {"БЦИЯ", "BSIYA"},
            {"БЦИОН", "BSION"},
            {"КЦИЯ", "KSIYA"},
            {"КЦИОН", "KSION"},
            {"НЦИЯ", "NSIYA"},
            {"НЦИОН", "NSION"},
            {"РЦИЯ", "RSIYA"},
            {"РЦИОН", "RSION"},
            {"ПЦИЯ", "PSIYA"},
            {"ПЦИОН", "PSION"},
            {"ЦИЯ", "TSIYA"},
            {"ЦИСТ", "TSIST"},
            {"ЦИЗМ", "TSIZM"},
            {"ЦИТ", "TSIT"},
            {"ЦЕВТ", "TSEVT"},
            {"ЦЕПТ", "TSEPT"},
            {"ЦЕР", "TSER"},
            {"ЦИА", "TSIA"},
            {"ЦИА", "SIA"},
            {"ЦИКЛ", "TSIKL"},
            {"ЦИО", "TSIO"},
            {"ЦИУ", "TSIU"},
            {"ЦИУ", "SIU"},
    };


//    "ц"  ts
//{" е", " ye"},
    //"ъ" "’" "ъ"
    //"ь" ""
    //q,g', x, h, o', yo, yu, ya, Ь,
}
