package uz.alvasti.lotinkirill.wordtranslator;

import uz.alvasti.lotinkirill.utils.CustomArrayUtil;

import java.util.*;

public class WordsLibrary implements Translate {

    private static Map<Integer, List<String>> cyrillicLatinWords;
    private static Map<Integer, List<String>> latinCyrillicWords;

    public boolean checkLatin(String word) {

        return WordsLibrary.latinCyrillicWords.containsKey(word.hashCode());
    }

    public boolean checkKirill(String word) {

        return WordsLibrary.cyrillicLatinWords.containsKey(word.hashCode());
    }

    @Override
    public String translateToLatin(String word) {

        return translateWithHashMap(WordsLibrary.cyrillicLatinWords, word);
    }

    @Override
    public String translateToCyrillic(String word) {
        return translateWithHashMap(WordsLibrary.latinCyrillicWords, word);
    }

    /**
     * camelCase, PascalCase yaxshi ishlamasligi mumkin
     * working correctly lower case, UPPER CASE, Capital Case
     */
    private String translateWithHashMap(Map<Integer, List<String>> wordsCompabilityMap, String word) {

        LETTER_CASES wordCase = null;
        if (word.toUpperCase().equals(word)) {
            wordCase = LETTER_CASES.UPPER_CASE;
        } else {
            if (word.toLowerCase().equals(word)) {
                wordCase = LETTER_CASES.LOWER_CASE;
            } else {
                if (word.length() > 1) {
                    String firstLetter = word.charAt(0) + "";
                    String otherLetters = word.substring(1);
                    if (firstLetter.toUpperCase().equals(firstLetter) &&
                            otherLetters.toLowerCase().equals(otherLetters)) {
                        wordCase = LETTER_CASES.CAMEL_CASE;
                    }
                } else {
                    return word;
                }
            }
        }

        if (wordCase == null) {
            return word;
        }
        var wordsChar = word.toLowerCase().toCharArray();

        boolean isHave = true;
        while (isHave) {
            isHave = false;
            int len = wordsChar.length;

            for (int i = 0; i < len && !isHave; i++) {

                for (int j = len; j >= i + 1 && !isHave; j--) {

                    String s = String.valueOf(Arrays.copyOfRange(wordsChar, i, j));
                    var list = wordsCompabilityMap.get(s.hashCode());

                    if (list != null) {
                        wordsChar = CustomArrayUtil.concatCharArrays(
                                Arrays.copyOfRange(wordsChar, 0, i),
                                list.get(0).toCharArray(),
                                Arrays.copyOfRange(wordsChar, j, len));
                        isHave = true;
                    }
                }
            }
        }

        String result = word;
        switch (wordCase) {
            case UPPER_CASE: {
                result = String.valueOf(wordsChar).toUpperCase();
                break;
            }
            case LOWER_CASE: {
                result = String.valueOf(wordsChar).toLowerCase();
                break;
            }
            default: {

                String firstLetter = wordsChar[0] + "";
                result = firstLetter.toUpperCase() + String.valueOf(wordsChar, 1, wordsChar.length - 1).toLowerCase();
                break;
            }
        }
        return result;
    }

    private static String[][] words;

    /**
     * “Ц” ҳарфи иштирок этган сўзларнинг имлоси
     *
     * @link http://xushnudbek.blogspot.com/p/blog-page_1204.html
     * and from matn.uz
     * for(var key in r){
     * var val = r[key];
     * var index = val.indexOf("[");
     * if(index > -1){
     * console.log("{\""+key+"\", "+val.replace('[', '').replace(']','')+"\"},");
     * val = val.substr(0,index);
     * }
     * console.log("{\""+key+"\", "+val+"\"},");
     * };
     */
    private static final String[][] wordsInitial = {
            {"абстракция", "abstraksiya"},
            {"абцесс", "absess"},
            {"абцисса", "absissa"},
            {"авиация", "aviatsiya"},
            {"адаптация", "adaptatsiya"},
            {"адсорбция", "adsorbsiya"},
            {"акация", "akatsiya"},
            {"акклиматизация", "akklimatizatsiya"},
            {"аккредитация", "akkreditatsiya"},
            {"аккумуляция", "akkumulyatsiya"},
            {"активация", "aktivatsiya"},
            {"акцептор", "akseptor"},
            {"акцессор", "aksessor"},
            {"акциз", "aksiz"},
            {"акция", "aksiya"},
            {"аннотация", "annotatsiya"},
            {"антифрикцион", "antifriksion"},
            {"апелляция", "apellyatsiya"},
            {"апробация", "aprobatsiya"},
            {"ассимиляция", "assimilyatsiya"},
            {"ассоциация", "assotsiatsiya"},
            {"аттестация", "attestatsiya"},
            {"аукцион", "auksion"},
            {"ацетон", "atseton"},
            {"ацтек", "atstek"},
            {"баренц", "barens"},
            {"вадуц", "vaduts"},
            {"вакцина", "vaksina"},
            {"вариация", "variatsiya"},
            {"вегетация", "vegetatsiya"},
            {"венеция", "venetsiya"},
            {"вентиляция", "ventilyatsiya"},
            {"вибрация", "vibratsiya"},
            {"вице-", "vitse-"},
            {"гелиоцентрик", "geliotsentrik"},
            {"геоцентрик", "geotsentrik"},
            {"герц", "gers"},
            {"герцог", "gersog"},
            {"гидратация", "gidratatsiya"},
            {"глобализация", "globalizatsiya"},
            {"горчица", "gorchitsa"},
            {"гравитацион", "gravitatsion"},
            {"гравитация", "gravitatsiya"},
            {"греция", "gretsiya"},
            {"даймлер-бенц", "daymler-bens"},
            {"данциг", "dansig"},
            {"девальвация", "devalvatsiya"},
            {"дегустация", "degustatsiya"},
            {"дедукция", "deduksiya"},
            {"дезактивация", "dezaktivatsiya"},
            {"декламация", "deklamatsiya"},
            {"декларация", "deklaratsiya"},
            {"декорация", "dekoratsiya"},
            {"делегация", "delegatsiya"},
            {"делимитация", "delimitatsiya"},
            {"демаркация", "demarkatsiya"},
            {"денонсация", "denonsatsiya"},
            {"депортация", "deportatsiya"},
            {"деривация", "derivatsiya"},
            {"детонация", "detonatsiya"},
            {"дефицит", "defitsit"},
            {"деформация", "deformatsiya"},
            {"децибел", "detsibel"},
            {"дециметр", "detsimetr"},
            {"диверсификация", "diversifikatsiya"},
            {"дирекция", "direksiya"},
            {"дисквалификация", "diskvalifikatsiya"},
            {"дискриминация", "diskriminatsiya"},
            {"дислокация", "dislokatsiya"},
            {"диссертация", "dissertatsiya"},
            {"диссимиляция", "dissimilyatsiya"},
            {"дифференциал", "differensial"},
            {"дифференциация", "differensiatsiya"},
            {"дифференция", "differensiya"},
            {"донецк", "donetsk"},
            {"дотация", "dotatsiya"},
            {"доцент", "dotsent"},
            {"жиу-жицу", "jiu-jitsu"},
            {"изоляция", "izolyatsiya"},
            {"иллюстрация", "illyustratsiya"},
            {"иммобилизация", "immobilizatsiya"},
            {"импровизация", "improvizatsiya"},
            {"инвестиция", "investitsiya"},
            {"индексация", "indeksatsiya"},
            {"индукция", "induksiya"},
            {"индульгенция", "indulgensiya"},
            {"инерция", "inersiya"},
            {"инквизиция", "inkvizitsiya"},
            {"инкубация", "inkubatsiya"},
            {"инспекция", "inspeksiya"},
            {"инструкция", "instruksiya"},
            {"инсценировка", "inssenirovka"},
            {"интеграция", "integratsiya"},
            {"интервенция", "intervensiya"},
            {"интерференция", "interferensiya"},
            {"интуиция", "intuitsiya"},
            {"инфекция", "infeksiya"},
            {"инфляция", "inflyatsiya"},
            {"информацион", "informatsion"},
            {"иррационал", "irratsional"},
            {"ирригация", "irrigatsiya"},
            {"кальций", "kalsiy"},
            {"канализация", "kanalizatsiya"},
            {"канцлер", "kansler"},
            {"капитуляция", "kapitulyatsiya"},
            {"кассация", "kassatsiya"},
            {"католицизм", "katolitsizm"},
            {"квалификация", "kvalifikatsiya"},
            {"кварц", "kvars"},
            {"классификация", "klassifikatsiya"},
            {"классицизм", "klassitsizm"},
            {"коллекция", "kolleksiya"},
            {"колонизация", "kolonizatsiya"},
            {"комбинация", "kombinatsiya"},
            {"коммерция", "kommersiya"},
            {"коммуникация", "kommunikatsiya"},
            {"компенсация", "kompensatsiya"},
            {"композиция", "kompozitsiya"},
            {"конвекция", "konveksiya"},
            {"конвенция", "konvensiya"},
            {"консервация", "konservatsiya"},
            {"консолидация", "konsolidatsiya"},
            {"консорциум", "konsorsium"},
            {"консорция", "konsorsiya"},
            {"констанца", "konstansa"},
            {"конституция", "konstitutsiya"},
            {"конструкция", "konstruksiya"},
            {"консультация", "konsultatsiya"},
            {"конфедерация", "konfederatsiya"},
            {"конференция", "konferensiya"},
            {"концентрат", "konsentrat"},
            {"концентрация", "konsentratsiya"},
            {"концепт", "konsept"},
            {"концепция", "konsepsiya"},
            {"концерн", "konsern"},
            {"концерт", "konsert"},
            {"концессия", "konsessiya"},
            {"концлагерь", "konslager"},
            {"конъюнкция", "kon’yunksiya"},
            {"координация", "koordinatsiya"},
            {"корпорация", "korporatsiya"},
            {"коррекция", "korreksiya"},
            {"корреспонденция", "korrespondensiya"},
            {"коррупция", "korrupsiya"},
            {"коэффициент", "koeffitsiyent"},
            {"культивация", "kultivatsiya"},
            {"лактация", "laktatsiya"},
            {"Лейпциг", "Leypsig"},
            {"лейцит", "leysit"},
            {"лекция", "leksiya"},
            {"лицей", "litsey"},
            {"лицензия", "litsenziya"},
            {"лиценциат", "litsensiat"},
            {"майнц", "mayns"},
            {"марганец", "marganets"},
            {"марганцовка", "margansovka"},
            {"матрица", "matritsa"},
            {"мелиорация", "melioratsiya"},
            {"менингококкцемия", "meningokokksemiya"},
            {"Мерседес-бенц", "Mersedes-bens"},
            {"механизация", "mexanizatsiya"},
            {"миграция", "migratsiya"},
            {"милиция", "militsiya"},
            {"модернизация", "modernizatsiya"},
            {"модификация", "modifikatsiya"},
            {"модуляция", "modulyatsiya"},
            {"мотоцикл", "motosikl"},
            {"муниципал", "munitsipal"},
            {"муниципалитет", "munitsipalitet"},
            {"мутация", "mutatsiya"},
            {"мцири", "mtsiri"},
            {"навигация", "navigatsiya"},
            {"национализация", "natsionalizatsiya"},
            {"национализм", "natsionalizm"},
            {"нацист", "natsist"},
            {"ницца", "nitssa"},
            {"облигация", "obligatsiya"},
            {"оккупация", "okkupatsiya"},
            {"оксигенация", "oksigenatsiya"},
            {"операция", "operatsiya"},
            {"осциллограф", "ossillograf"},
            {"офицер", "ofitser"},
            {"патриций", "patritsiy"},
            {"плантация", "plantatsiya"},
            {"плацдарм", "platsdarm"},
            {"плацента", "platsenta"},
            {"позиция", "pozitsiya"},
            {"полиция", "politsiya"},
            {"популяция", "populyatsiya"},
            {"потенциал", "potensial"},
            {"принцип", "prinsip"},
            {"провинция", "provinsiya"},
            {"проекция", "proyeksiya"},
            {"пропорционал", "proporsional"},
            {"пропорция", "proporsiya"},
            {"процесс", "protsess"},
            {"публицист", "publitsist"},
            {"публицистик", "publitsistik"},
            {"радиация", "radiatsiya"},
            {"радиолокация", "radiolokatsiya"},
            {"ратификация", "ratifikatsiya"},
            {"рацион", "ratsion"},
            {"рационал", "ratsional"},
            {"реабилитация", "reabilitatsiya"},
            {"реакция", "reaksiya"},
            {"реализация", "realizatsiya"},
            {"реанимация", "reanimatsiya"},
            {"революция", "revolyutsiya"},
            {"регуляция", "regulyatsiya"},
            {"редакция", "redaksiya"},
            {"редукция", "reduksiya"},
            {"резервация", "rezervatsiya"},
            {"рекреация", "rekreatsiya"},
            {"репродукция", "reproduksiya"},
            {"рецепт", "retsept"},
            {"рецептор", "retseptor"},
            {"рецидивист", "retsidivist"},
            {"рицар", "ritsar"},
            {"сан-франциско", "san-fransisko"},
            {"седиментация", "sedimentatsiya"},
            {"секреция", "sekretsiya"},
            {"секция", "seksiya"},
            {"селекция", "seleksiya"},
            {"сепарация", "separatsiya"},
            {"сигнализация", "signalizatsiya"},
            {"Сицилия", "Sitsiliya"},
            {"сланец", "slanets"},
            {"социализм", "sotsializm"},
            {"социология", "sotsiologiya"},
            {"станция", "stansiya"},
            {"стационар", "statsionar"},
            {"ступица", "stupitsa"},
            {"сукцинат", "suksinat"},
            {"сценарий", "ssenariy"},
            {"сянцзи", "syanszi"},
            {"тенденция", "tendensiya"},
            {"транскрипция", "transkripsiya"},
            {"транснационал", "transnatsional"},
            {"трансформация", "transformatsiya"},
            {"трапеция", "trapetsiya"},
            {"унция", "unsiya"},
            {"фармацевтика", "farmatsevtika"},
            {"федерация", "federatsiya"},
            {"Флоренция", "Florensiya"},
            {"формация", "formatsiya"},
            {"фракция", "fraksiya"},
            {"франций", "fransiy"},
            {"франциск", "fransisk"},
            {"Франция", "Fransiya"},
            {"француз", "fransuz"},
            {"фрикцион", "friksion"},
            {"функция", "funksiya"},
            {"халцедон", "xalsedon"},
            {"холецистит", "xoletsistit"},
            {"цезий", "seziy"},
            {"цейтнот", "seytnot"},
            {"целлофан", "sellofan"},
            {"целлюлоза", "sellyuloza"},
            {"цельсий", "selsiy"},
            {"цемент", "sement"},
            {"цензор", "senzor"},
            {"цензура", "senzura"},
            {"центнер", "sentner"},
            {"цех", "sex"},
            {"цеце", "setse"},
            {"цеце", "setse"},
            {"цивилизация", "sivilizatsiya"},
            {"цикл", "sikl"},
            {"циклон", "siklon"},
            {"циклоп", "siklop"},
            {"цилиндр", "silindr"},
            {"цилиндрик", "silindrik"},
            {"цилиндрсимон", "silindrsimon"},
            {"цирк", "sirk"},
            {"циркуль", "sirkul"},
            {"циркуляция", "sirkulyatsiya"},
            {"цистерна", "sisterna"},
            {"цитрус", "sitrus"},
            {"черепица", "cherepitsa"},
            {"Швейцария", "Shveysariya"},
            {"Швеция", "Shvetsiya"},
            {"шприц", "shprits"},
            {"эволюция", "evolyutsiya"},
            {"эквиваленция", "ekvivalensiya"},
            {"экспедиция", "ekspeditsiya"},
            {"эксплуатация", "ekspluatatsiya"},
            {"экспозиция", "ekspozitsiya"},
            {"экстракция", "ekstraksiya"},
            {"эксцентриситет", "ekssentrisitet"},
            {"электрострикция", "elektrostriksiya"},
            {"эмансипация", "emansipatsiya"},
            {"эмиграция", "emigratsiya"},
            {"эмоция", "emotsiya"},
            {"энциклопедик", "ensiklopedik"},
            {"энциклопедия", "ensiklopediya"},
            {"эпилейцит", "epileysit"},
            {"эпицентр", "epitsentr"},
            {"эссенция", "essensiya"},
            {"юрисдикция", "yurisdiksiya"},
            {"юриспруденция", "yurisprudensiya"},
            {"янцзи", "yanszi"},
            {"сентябр", "sentabr"},
            {"сентябр", "sentyabr"},
            {"октябрь", "oktabr"},
            {"октябрь", "oktyabr"},
            {"бюджет", "budjet"},
            {"меценат", "mesenat"},
            {"нуқтаи назар", "nuqtayi nazar"},
            {"биолюминесценция", "biolyuminessensiya"},
            {"дифференциация", "differensiatsiya"},
            {"галлюцинация", "gallyutsinatsiya"},
            {"телеинсценировка", "teleinssenirovka"},
            {"люминесценция", "lyuminessensiya"},
            {"рекогносцировка", "rekognossirovka"},
            {"цитодиагностика", "sitodiagnostika"},
            {"бронеавтомобиль", "broneavtomobil"},
            {"бронеавтомобил", "broneavtomobil"},
            {"диссоциация", "dissotsiatsiya"},
            {"нитроглицерин", "nitroglitserin"},
            {"штангенциркуль", "shtangensirkul"},
            {"штангенциркул", "shtangensirkul"},
            {"альма-терапия", "alma-terapiya"},
            {"автомагистраль", "avtomagistral"},
            {"автомагистрал", "avtomagistral"},
            {"гелиоцентрик", "geliotsentrik"},
            {"коэффициент", "koeffitsiyent"},
            {"полицмейстер", "politsmeyster"},
            {"предохранитель", "predoxranitel"},
            {"предохранител", "predoxranitel"},
            {"радиоспектакль", "radiospektakl"},
            {"радиоспектакл", "radiospektakl"},
            {"реэмиграция", "reemigratsiya"},
            {"реэвакуация", "reevakuatsiya"},
            {"цивилизация", "sivilizatsiya"},
            {"девальвация", "devalvatsiya"},
            {"инсценировка", "inssenirovka"},
            {"капельмейстер", "kapelmeyster"},
            {"кинофестиваль", "kinofestival"},
            {"кинофестивал", "kinofestival"},
            {"киносценарий", "kinossenariy"},
            {"левомицетин", "levomitsetin"},
            {"пульверизатор", "pulverizator"},
            {"ревальвация", "revalvatsiya"},
            {"сутэмизувчи", "sutemizuvchi"},
            {"виключатель", "viklyuchatel"},
            {"виключател", "viklyuchatel"},
            {"юрисконсульт", "yuriskonsult"},
            {"автоприцеп", "avtopritsep"},
            {"бактерицид", "bakteritsid"},
            {"бруцеллёз", "brutsellyoz"},
            {"фельдмаршал", "feldmarshal"},
            {"геоцентрик", "geotsentrik"},
            {"гляциолог", "glyatsiolog"},
            {"киноконцерт", "kinokonsert"},
            {"конферансье", "konferansye"},
            {"микроинсульт", "mikroinsult"},
            {"монокультура", "monokultura"},
            {"пенициллин", "penitsillin"},
            {"пресс-папье", "press-papye"},
            {"реципиент", "retsipiyent"},
            {"шмуцтитул", "shmutstitul"},
            {"включатель", "vklyuchatel"},
            {"включател", "vklyuchatel"},
            {"холецистит", "xoletsistit"},
            {"адъюнктура", "adyunktura"},
            {"адъюнкт", "adyunkt"},
            {"большевизм", "bolshevizm"},
            {"броненосец", "bronenoses"},
            {"черепица", "cherepitsa"},
            {"эскадрилья", "eskadrilya"},
            {"физкультура", "fizkultura"},
            {"фортепьяно", "fortepyano"},
            {"фотоателье", "fotoatelye"},
            {"гипосульфит", "giposulfit"},
            {"гипоцентр", "gipotsentr"},
            {"горизонталь", "gorizontal"},
            {"горизонтал", "gorizontal"},
            {"готовальний", "gotovalniy"},
            {"канцероген", "kanserogen"},
            {"кастрюлька", "kastryulka"},
            {"колонцифра", "kolonsifra"},
            {"концепция", "konsepsiya"},
            {"концессия", "konsessiya"},
            {"коррупция", "korrupsiya"},
            {"лицензия", "litsenziya"},
            {"марсельеза", "marselyeza"},
            {"меньшевизм", "menshevizm"},
            {"микрорайон", "mikrorayon"},
            {"мизансцена", "mizanssena"},
            {"муниципал", "munitsipal"},
            {"офтальмолог", "oftalmolog"},
            {"пальпация", "palpatsiya"},
            {"почтальон", "pochtalyon"},
            {"пульмонолог", "pulmonolog"},
            {"қайнэгачи", "qaynegachi"},
            {"рецензент", "retsenzent"},
            {"рецензия", "retsenziya"},
            {"целлюлоза", "sellyuloza"},
            {"центрифуга", "sentrifuga"},
            {"цитология", "sitologiya"},
            {"сцинтиграф", "ssintigraf"},
            {"тенденциоз", "tendensioz"},
            {"уборшица", "uborshitsa"},
            {"валерьянка", "valeryanka"},
            {"вальвация", "valvatsiya"},
            {"виолончель", "violonchel"},
            {"виолончел", "violonchel"},
            {"холодильник", "xolodilnik"},
            {"арьергард", "aryergard"},
            {"ацетилен", "atsetilen"},
            {"авианосец", "avianoses"},
            {"автомобиль", "avtomobil"},
            {"автомобил", "avtomobil"},
            {"биомицин", "biomitsin"},
            {"большевик", "bolshevik"},
            {"бюллетень", "byulleten"},
            {"бюллетен", "byulleten"},
            {"эпицентр", "epitsentr"},
            {"фельдъегерь", "feldyeger"},
            {"фельдъегер", "feldyeger"},
            {"фотоальбом", "fotoalbom"},
            {"геральдика", "geraldika"},
            {"гербицид", "gerbitsid"},
            {"глицерин", "glitserin"},
            {"горчица", "gorchitsa"},
            {"гусеница", "gusenitsa"},
            {"инъекция", "inyeksiya"},
            {"катапульта", "katapulta"},
            {"компаньон", "kompanyon"},
            {"компьютер", "kompyuter"},
            {"конференц", "konferens"},
            {"конфуций", "konfutsiy"},
            {"концлагерь", "konslager"},
            {"концлагер", "konslager"},
            {"культуризм", "kulturizm"},
            {"лютеций", "lyutetsiy"},
            {"магистраль", "magistral"},
            {"магистрал", "magistral"},
            {"медицина", "meditsina"},
            {"меньшевик", "menshevik"},
            {"микрофильм", "mikrofilm"},
            {"миноносец", "minonoses"},
            {"официант", "ofitsiant"},
            {"оккультизм", "okkultizm"},
            {"ординарец", "ordinares"},
            {"пацифист", "patsifist"},
            {"пацифизм", "patsifizm"},
            {"пациент", "patsiyent"},
            {"пестицид", "pestitsid"},
            {"плацдарм", "platsdarm"},
            {"плацкарт", "platskart"},
            {"плебисцит", "plebissit"},
            {"целлулоид", "selluloid"},
            {"циферблат", "siferblat"},
            {"циркуляр", "sirkulyar"},
            {"цитокимё", "sitokimyo"},
            {"социолог", "sotsiolog"},
            {"специфик", "spetsifik"},
            {"технеций", "texnetsiy"},
            {"ультиматум", "ultimatum"},
            {"умивальник", "umivalnik"},
            {"вермишель", "vermishel"},
            {"вермишел", "vermishel"},
            {"вестибюль", "vestibyul"},
            {"вестибюл", "vestibyul"},
            {"видеофильм", "videofilm"},
            {"акционер", "aksioner"},
            {"альбатрос", "albatros"},
            {"альпинист", "alpinist"},
            {"альпинизм", "alpinizm"},
            {"амальгама", "amalgama"},
            {"арьергард", "arergard"},
            {"бандероль", "banderol"},
            {"бандерол", "banderol"},
            {"барельеф", "barelyef"},
            {"батальон", "batalyon"},
            {"бацилла", "batsilla"},
            {"бельведер", "belveder"},
            {"биофильтр", "biofiltr"},
            {"браконьер", "brakoner"},
            {"будильник", "budilnik"},
            {"бульденеж", "buldenej"},
            {"бульдозер", "buldozer"},
            {"диагональ", "diagonal"},
            {"диагонал", "diagonal"},
            {"дирижабль", "dirijabl"},
            {"дирижабл", "dirijabl"},
            {"двигатель", "dvigatel"},
            {"двигател", "dvigatel"},
            {"эмульсия", "emulsiya"},
            {"эндшпиль", "endshpil"},
            {"эндшпил", "endshpil"},
            {"фагоцит", "fagotsit"},
            {"фальсифик", "falsifik"},
            {"фельдшер", "feldsher"},
            {"фестиваль", "festival"},
            {"фестивал", "festival"},
            {"фитонцид", "fitonsid"},
            {"гаубица", "gaubitsa"},
            {"геноцид", "genotsid"},
            {"гиацинт", "giatsint"},
            {"госпиталь", "gospital"},
            {"госпитал", "gospital"},
            {"интервью", "intervyu"},
            {"инвентарь", "inventar"},
            {"инвентар", "inventar"},
            {"календарь", "kalendar"},
            {"календар", "kalendar"},
            {"калькуля", "kalkulya"},
            {"кастрюль", "kastryul"},
            {"кастрюл", "kastryul"},
            {"кинофильм", "kinofilm"},
            {"концентр", "konsentr"},
            {"консульта", "konsulta"},
            {"конвейер", "konveyer"},
            {"марганец", "marganes"},
            {"матрица", "matritsa"},
            {"медальон", "medalyon"},
            {"модельер", "modelyer"},
            {"монастирь", "monastir"},
            {"монастир", "monastir"},
            {"нимпальто", "nimpalto"},
            {"параллель", "parallel"},
            {"параллел", "parallel"},
            {"павильон", "pavilyon"},
            {"печенье", "pechenye"},
            {"петлица", "petlitsa"},
            {"пойабзал", "poyabzal"},
            {"пойафзал", "poyafzal"},
            {"пойандоз", "poyandoz"},
            {"пойустун", "poyustun"},
            {"процент", "protsent"},
            {"процесс", "protsess"},
            {"рентабель", "rentabel"},
            {"рентабел", "rentabel"},
            {"рецидив", "retsidiv"},
            {"револьвер", "revolver"},
            {"рубильник", "rubilnik"},
            {"секретарь", "sekretar"},
            {"секретар", "sekretar"},
            {"сельдерей", "selderey"},
            {"целлофан", "sellofan"},
            {"сентябрь", "sentyabr"},
            {"сентябр", "sentyabr"},
            {"шифоньер", "shifoner"},
            {"шницель", "shnitsel"},
            {"шницел", "shnitsel"},
            {"шпиндель", "shpindel"},
            {"шпиндел", "shpindel"},
            {"штемпель", "shtempel"},
            {"штемпел", "shtempel"},
            {"штепсель", "shtepsel"},
            {"штепсел", "shtepsel"},
            {"швейцар", "shveysar"},
            {"силиций", "silitsiy"},
            {"цистерна", "sisterna"},
            {"спектакль", "spektakl"},
            {"спектакл", "spektakl"},
            {"сценарий", "ssenariy"},
            {"стронций", "stronsiy"},
            {"таблица", "tablitsa"},
            {"телефильм", "telefilm"},
            {"теплица", "teplitsa"},
            {"ведомость", "vedomost"},
            {"ведомост", "vedomost"},
            {"абсцесс", "abssess"},
            {"акварель", "akletel"},
            {"акварел", "akletel"},
            {"алкоголь", "alkogol"},
            {"алкогол", "alkogol"},
            {"ансамбль", "ansambl"},
            {"ансамбл", "ansambl"},
            {"апельсин", "apelsin"},
            {"ацетон", "atseton"},
            {"бельэтаж", "beletaj"},
            {"бельгия", "belgiya"},
            {"бельтинг", "belting"},
            {"бильярд", "bilyard"},
            {"болонья", "bolonya"},
            {"боцман", "botsman"},
            {"диафильм", "diafilm"},
            {"доцент", "dotsent"},
            {"энцефал", "ensefal"},
            {"эсминец", "esmines"},
            {"фельетон", "feleton"},
            {"фольклор", "folklor"},
            {"француз", "fransuz"},
            {"гастроль", "gastrol"},
            {"гастрол", "gastrol"},
            {"гельминт", "gelmint"},
            {"горельеф", "gorelef"},
            {"интерьер", "interer"},
            {"итальян", "italyan"},
            {"женьшень", "jenshen"},
            {"женьшен", "jenshen"},
            {"канифоль", "kanifol"},
            {"канифол", "kanifol"},
            {"канцлер", "kansler"},
            {"капсюль", "kapsyul"},
            {"капсюл", "kapsyul"},
            {"карамель", "karamel"},
            {"карамел", "karamel"},
            {"картечь", "kartech"},
            {"картеч", "kartech"},
            {"карусель", "karusel"},
            {"карусел", "karusel"},
            {"коктейль", "kokteyl"},
            {"коктейл", "kokteyl"},
            {"концерн", "konsern"},
            {"концерт", "konsert"},
            {"контроль", "kontrol"},
            {"контрол", "kontrol"},
            {"конъюнктура", "konyunktura"},
            {"коньюктивит", "konyuktivit"},
            {"кульмина", "kulmina"},
            {"культива", "kultiva"},
            {"лоцман", "lotsman"},
            {"майонез", "mayonez"},
            {"мельхиор", "melxior"},
            {"мольберт", "molbert"},
            {"офицер", "ofitser"},
            {"октябрь", "oktyabr"},
            {"октябр", "oktyabr"},
            {"партьер", "partyer"},
            {"пенальти", "penalti"},
            {"пластирь", "plastir"},
            {"пластир", "plastir"},
            {"поршень", "porshen"},
            {"поршен", "porshen"},
            {"портфель", "portfel"},
            {"портфел", "portfel"},
            {"премьер", "premyer"},
            {"пристань", "pristan"},
            {"пристан", "pristan"},
            {"прицеп", "pritsep"},
            {"разъезд", "razyezd"},
            {"рецепт", "retsept"},
            {"центнер", "sentner"},
            {"цензура", "senzura"},
            {"цесарка", "sesarka"},
            {"цейтнот", "seytnot"},
            {"шагрень", "shagren"},
            {"шагрен", "shagren"},
            {"шампунь", "shampun"},
            {"шампун", "shampun"},
            {"шпатель", "shpatel"},
            {"шпател", "shpatel"},
            {"шпилька", "shpilka"},
            {"штапель", "shtapel"},
            {"штапел", "shtapel"},
            {"цилиндр", "silindr"},
            {"цитолиз", "sitoliz"},
            {"скальпель", "skalpel"},
            {"скальпел", "skalpel"},
            {"стержень", "sterjen"},
            {"стержен", "sterjen"},
            {"субъект", "subyekt"},
            {"текстиль", "tekstil"},
            {"текстил", "tekstil"},
            {"вакцина", "vaksina"},
            {"варьете", "letyete"},
            {"верньер", "vernyer"},
            {"виньетка", "vinetka"},
            {"водевиль", "vodevil"},
            {"водевил", "vodevil"},
            {"вольфрам", "volfram"},
            {"хрусталь", "xrustal"},
            {"хрустал", "xrustal"},
            {"акцент", "aksent"},
            {"акция", "aksiya"},
            {"альянс", "alyans"},
            {"артикль", "artikl"},
            {"артикл", "artikl"},
            {"асфальт", "asfalt"},
            {"ателье", "atelye"},
            {"бальнео", "balneo"},
            {"бальзам", "balzam"},
            {"барьер", "baryer"},
            {"баррель", "barrel"},
            {"баррел", "barrel"},
            {"базальт", "bazalt"},
            {"бинокль", "binokl"},
            {"бинокл", "binokl"},
            {"бульдог", "buldog"},
            {"бульон", "bulyon"},
            {"бульвар", "bullet"},
            {"чизель", "chizel"},
            {"чизел", "chizel"},
            {"дальтон", "dalton"},
            {"декабрь", "dekabr"},
//            {"декабр", "dekabr"},
            {"дельфин", "delfin"},
            {"факульт", "fakult"},
            {"февраль", "fevral"},
            {"феврал", "fevral"},
            {"гальван", "galvan"},
            {"гантель", "gantel"},
            {"гантел", "gantel"},
            {"гармонь", "garmon"},
            {"гармон", "garmon"},
            {"герцог", "gersog"},
            {"грифель", "grifel"},
            {"грифел", "grifel"},
            {"импульс", "impuls"},
            {"инсульт", "insult"},
            {"кальций", "kalsiy"},
            {"каратэ", "karate"},
            {"карьер", "karyer"},
            {"картель", "kartel"},
            {"картел", "kartel"},
            {"кобальт", "kobalt"},
            {"коньяк", "konyak"},
            {"кровать", "krovat"},
            {"кроват", "krovat"},
            {"курьер", "kuryer"},
            {"ланцет", "lanset"},
            {"лицей", "litsey"},
            {"лосьон", "losyon"},
            {"мигрень", "migren"},
            {"мигрен", "migren"},
            {"мойупа", "moyupa"},
            {"ниппель", "nippel"},
            {"ниппел", "nippel"},
            {"ноябрь", "noyabr"},
            {"ноябр", "noyabr"},
            {"область", "oblast"},
            {"област", "oblast"},
            {"объект", "obyekt"},
            {"патруль", "patrul"},
            {"патрул", "patrul"},
            {"печать", "pechat"},
            {"печат", "pechat"},
            {"пинцет", "pinset"},
            {"пицца", "pitssa"},
            {"плейер", "pleyer"},
            {"повесть", "povest"},
            {"повест", "povest"},
            {"профиль", "profil"},
            {"профил", "profil"},
            {"пульпит", "pulpit"},
            {"рантье", "rantye"},
            {"рельеф", "relyef"},
            {"ретушь", "retush"},
            {"ретуш", "retush"},
            {"рицарь", "ritsar"},
            {"рицар", "ritsar"},
            {"цельсий", "selsiy"},
            {"цемент", "sement"},
            {"сеньор", "senyor"},
            {"цензор", "senzor"},
            {"шинель", "shinel"},
            {"шинел", "shinel"},
            {"шприц", "shpris"},
            {"циркуль", "sirkul"},
            {"циркул", "sirkul"},
            {"цирроз", "sirroz"},
            {"цистит", "sistit"},
            {"цитата", "sitata"},
            {"цитрус", "sitrus"},
            {"сланец", "slanes"},
            {"слесарь", "slesar"},
            {"слесар", "slesar"},
            {"спираль", "spiral"},
            {"спирал", "spiral"},
            {"статья", "statya"},
            {"стайер", "stayer"},
            {"стелька", "stelka"},
            {"сульфат", "sulfat"},
            {"цунами", "sunami"},
            {"съёмка", "syomka"},
            {"терцет", "terset"},
            {"тоннель", "tonnel"},
            {"тоннел", "tonnel"},
            {"туннель", "tunnel"},
            {"туннел", "tunnel"},
            {"тюлень", "tyulen"},
            {"тюлен", "tyulen"},
            {"вексель", "veksel"},
            {"вексел", "veksel"},
            {"вельвет", "velvet"},
            {"вентиль", "ventil"},
            {"вентил", "ventil"},
            {"вимпель", "vimpel"},
            {"вимпел", "vimpel"},
            {"волость", "volost"},
            {"волост", "volost"},
            {"вульгар", "vulgar"},
            {"январь", "yanlet"},
            {"январ", "yanlet"},
            {"йогурт", "yogurt"},
            {"абзац", "abzas"},
            {"акциз", "aksiz"},
            {"альбом", "albom"},
            {"апрель", "aprel"},
            {"апрел", "aprel"},
            {"артель", "artel"},
            {"артел", "artel"},
            {"дельта", "delta"},
            {"деталь", "detal"},
            {"детал", "detal"},
            {"дизель", "dizel"},
            {"дизел", "dizel"},
            {"фильтр", "filtr"},
            {"фольга", "folga"},
            {"фонарь", "fonar"},
            {"фонар", "fonar"},
            {"гавань", "gavan"},
            {"гаван", "gavan"},
            {"гильза", "gilza"},
            {"гуашь", "guash"},
            {"гуаш", "guash"},
            {"кабель", "kabel"},
            {"кабел", "kabel"},
            {"кафель", "kafel"},
            {"кафел", "kafel"},
            {"калька", "kalka"},
            {"кисель", "kisel"},
            {"кисел", "kisel"},
            {"китель", "kitel"},
            {"кител", "kitel"},
            {"князь", "knyaz"},
            {"княз", "knyaz"},
            {"коньки", "konki"},
            {"кремль", "kreml"},
            {"кремл", "kreml"},
            {"кварц", "klets"},
            {"лагерь", "lager"},
            {"лагер", "lager"},
            {"латунь", "latun"},
            {"латун", "latun"},
            {"лосось", "losos"},
            {"лосос", "losos"},
            {"майор", "mayor"},
            {"мебель", "mebel"},
            {"мебел", "mebel"},
            {"медаль", "medal"},
            {"медал", "medal"},
            {"модель", "model"},
            {"модел", "model"},
            {"мотель", "motel"},
            {"мотел", "motel"},
            {"мульти", "multi"},
            {"ненец", "nenes"},
            {"никель", "nikel"},
            {"никел", "nikel"},
            {"пальма", "palma"},
            {"пальто", "palto"},
            {"панель", "panel"},
            {"панел", "panel"},
            {"пароль", "parol"},
            {"парол", "parol"},
            {"педаль", "pedal"},
            {"педал", "pedal"},
            {"полька", "polka"},
            {"пульпа", "pulpa"},
            {"пьеса", "pyesa"},
            {"ранец", "ranes"},
            {"район", "rayon"},
            {"рэкет", "reket"},
            {"резьба", "rezba"},
            {"риель", "riyel"},
            {"риел", "riyel"},
            {"рояль", "royal"},
            {"роял", "royal"},
            {"сальдо", "saldo"},
            {"сальто", "salto"},
            {"цанга", "sanga"},
            {"цапфа", "sapfa"},
            {"цедра", "sedra"},
            {"церий", "seriy"},
            {"цезий", "seziy"},
            {"цинга", "singa"},
            {"синька", "sinka"},
            {"сирень", "siren"},
            {"сирен", "siren"},
            {"соболь", "sobol"},
            {"собол", "sobol"},
            {"цоколь", "sokol"},
            {"цокол", "sokol"},
            {"судья", "sudya"},
            {"съезд", "syezd"},
            {"табель", "tabel"},
            {"табел", "tabel"},
            {"тигель", "tigel"},
            {"тигел", "tigel"},
            {"токарь", "tokar"},
            {"токар", "tokar"},
            {"ультра", "ultra"},
            {"ваниль", "vanil"},
            {"ванил", "vanil"},
            {"якорь", "yakor"},
            {"якор", "yakor"},
            {"альфа", "alfa"},
            {"бронь", "bron"},
            {"брон", "bron"},
            {"дрель", "drel"},
            {"дрел", "drel"},
            {"дуэль", "duel"},
            {"дуэл", "duel"},
            {"эмаль", "emal"},
            {"эмал", "emal"},
            {"фильм", "film"},
            {"фойе", "foye"},
            {"фриц", "fris"},
            {"герц", "gers"},
            {"гольф", "golf"},
            {"июль", "iyul"},
            {"июл", "iyul"},
            {"июнь", "iyun"},
            {"июн", "iyun"},
            {"кьят", "kyat"},
            {"нефть", "neft"},
            {"нефт", "neft"},
            {"отель", "otel"},
            {"отел", "otel"},
            {"печь", "pech"},
            {"печ", "pech"},
            {"пульс", "puls"},
            {"пульт", "pult"},
            {"рельс", "rels"},
            {"рубль", "rubl"},
            {"рубл", "rubl"},
            {"сельдь", "seld"},
            {"сельд", "seld"},
            {"цент", "sent"},
            {"ценз", "senz"},
            {"циан", "sian"},
            {"цикл", "sikl"},
            {"цинк", "sink"},
            {"цирк", "sirk"},
            {"стиль", "stil"},
            {"стил", "stil"},
            {"тальк", "talk"},
            {"тюль", "tyul"},
            {"тюл", "tyul"},
            {"утиль", "util"},
            {"утил", "util"},
            {"вальс", "vals"},
            {"верфь", "verf"},
            {"верф", "verf"},
            {"вольт", "volt"},
            {"йога", "yoga"},
            {"юань", "yuan"},
            {"юан", "yuan"},
            {"альт", "alt"},
            {"миль", "mil"},
            {"мил", "mil"},
            {"ноль", "nol"},
            {"нол", "nol"},
            {"роль", "rol"},
            {"рол", "rol"},
            {"руль", "rul"},
            {"рул", "rul"},
            {"цех", "sex"},
            {"янада", "yana-da"},
            {"сирка", "sirka"},
            {"сингари", "singari"},
            {"принцип", "prinsip"},
            {"деци", "detsi"},
            {"цикл", "sikl"},
            {"вице", "vitse"},
            {"девальвация", "devalvatsiya"},
            {"вальвация", "valvatsiya"},
            {"пенсия", "pensiya"},
            {"версия", "versiya"},
            {"жинсият", "jinsiyat"},
            {"сирка", "sirka"},
            {"сингари", "singari"},
            {"принцип", "prinsp"},
            {"деци", "detsi"},
            {"цикл", "sikl"},
            {"вице", "Vitse"},
            {"девальвация", "devalvatsiya"},
            {"вальвация", "valvatsiya"},
            {"версия", "versiya"},
            {"жинсият", "jinsiyat"}

    };

    static {

        List<String[]> wordsList = new ArrayList<>();
        for (String[] word : WordsLibrary.wordsInitial) {
            if (!word[0].equals(word[0].toLowerCase()) && word[1].equals(word[1].toLowerCase())) {
                String[] wordTemp = new String[2];
                wordTemp[0] = word[0].toLowerCase();
                wordTemp[1] = word[1].toLowerCase();
                wordsList.add(wordTemp);
            }
        }
        int wordsInitialLength = WordsLibrary.wordsInitial.length;
        int len = wordsInitialLength + wordsList.size();
        WordsLibrary.words = new String[len][2];

        System.arraycopy(WordsLibrary.wordsInitial, 0, WordsLibrary.words, 0, wordsInitialLength);

        for (String[] word : wordsList) {
            WordsLibrary.words[wordsInitialLength++] = word;
        }

        var cyrillicLatinWords = new HashMap<Integer, List<String>>();
        var latinCyrillicWords = new HashMap<Integer, List<String>>();
        for (String[] word : WordsLibrary.words) {
            int hash0 = word[0].hashCode();
            int hash1 = word[1].hashCode();
            cyrillicLatinWords.computeIfAbsent(hash0, k -> new ArrayList<>());
            latinCyrillicWords.computeIfAbsent(hash1, k -> new ArrayList<>());
            cyrillicLatinWords.get(hash0).add(word[1]);
            latinCyrillicWords.get(hash1).add(word[0]);
        }

        cyrillicLatinWords.forEach((key, value) -> value.sort(Comparator.comparing(String::length).reversed()));
        latinCyrillicWords.forEach((key, value) -> value.sort(Comparator.comparing(String::length).reversed()));
        WordsLibrary.cyrillicLatinWords = Map.copyOf(cyrillicLatinWords);
        WordsLibrary.latinCyrillicWords = Map.copyOf(latinCyrillicWords);
    }

    private enum LETTER_CASES {
        CAMEL_CASE,
        UPPER_CASE,
        LOWER_CASE
    }
}


