package uz.alvasti.lotinkirill.wordtranslator;

import uz.alvasti.lotinkirill.utils.CustomArrayUtil;

import java.util.*;

public class WordsLibrary implements Translate {

    private static final Map<Integer, List<String>> cyrillicLatinWords = new HashMap<>();
    private static final Map<Integer, List<String>> latinCyrillicWords = new HashMap<>();

    public boolean checkLatin(String word) {

        return WordsLibrary.latinCyrillicWords.containsKey(word.hashCode());
    }

    public boolean checkKirill(String word) {

        return WordsLibrary.cyrillicLatinWords.containsKey(word.hashCode());
    }

    @Override
    public String translateToLatin(String word) {

        return translateWithHashMap(WordsLibrary.cyrillicLatinWords, word);
    }

    @Override
    public String translateToCyrillic(String word) {
        return translateWithHashMap(WordsLibrary.latinCyrillicWords, word);
    }

    /**
     * camelCase, PascalCase yaxshi ishlamasligi mumkin
     * working correctly lower case, UPPER CASE, Capital Case
     */
    private String translateWithHashMap(final Map<Integer, List<String>> wordsCompabilityMap, String word) {

        LETTER_CASES wordCase = null;
        if (word.toUpperCase().equals(word)) {
            wordCase = LETTER_CASES.UPPER_CASE;
        } else {
            if (word.toLowerCase().equals(word)) {
                wordCase = LETTER_CASES.LOWER_CASE;
            } else {
                if (word.length() > 1) {
                    String firstLetter = word.charAt(0) + "";
                    String otherLetters = word.substring(1);
                    if (firstLetter.toUpperCase().equals(firstLetter) &&
                            otherLetters.toLowerCase().equals(otherLetters)) {
                        wordCase = LETTER_CASES.CAMEL_CASE;
                    }
                } else {
                    return word;
                }
            }
        }

        if (wordCase == null) {
            return word;
        }
        var wordsChar = word.toLowerCase().toCharArray();

        boolean isHave = true;
        while (isHave) {
            isHave = false;
            int len = wordsChar.length;

            for (int i = 0; i < len && !isHave; i++) {

                for (int j = len; j >= i + 1 && !isHave; j--) {

                    String s = String.valueOf(Arrays.copyOfRange(wordsChar, i, j));
                    var list = wordsCompabilityMap.get(s.hashCode());

                    if (list != null) {
                        wordsChar = CustomArrayUtil.concatCharArrays(
                                Arrays.copyOfRange(wordsChar, 0, i),
                                list.get(0).toCharArray(),
                                Arrays.copyOfRange(wordsChar, j, len));
                        isHave = true;
                    }
                }
            }
        }

        String result = word;
        switch (wordCase) {
            case UPPER_CASE: {
                result = String.valueOf(wordsChar).toUpperCase();
                break;
            }
            case LOWER_CASE: {
                result = String.valueOf(wordsChar).toLowerCase();
                break;
            }
            default: {

                String firstLetter = wordsChar[0] + "";
                result = firstLetter.toUpperCase() + String.valueOf(wordsChar, 1, wordsChar.length - 1).toLowerCase();
                break;
            }
        }
        return result;
    }

    private static String[][] words;

    /**
     * “Ц” ҳарфи иштирок этган сўзларнинг имлоси
     *
     * @link http://xushnudbek.blogspot.com/p/blog-page_1204.html
     * and from matn.uz
     * for(var key in r){
     * var val = r[key];
     * var index = val.indexOf("[");
     * if(index > -1){
     * console.log("{\""+key+"\", "+val.replace('[', '').replace(']','')+"\"},");
     * val = val.substr(0,index);
     * }
     * console.log("{\""+key+"\", "+val+"\"},");
     * };
     */
    private static final String[][] wordsInitial = {
            {"абстракция", "abstraksiya"},
            {"абцесс", "absess"},
            {"абцисса", "absissa"},
            {"авиация", "aviatsiya"},
            {"адаптация", "adaptatsiya"},
            {"адсорбция", "adsorbsiya"},
            {"акация", "akatsiya"},
            {"акклиматизация", "akklimatizatsiya"},
            {"аккредитация", "akkreditatsiya"},
            {"аккумуляция", "akkumulyatsiya"},
            {"активация", "aktivatsiya"},
            {"акцептор", "akseptor"},
            {"акцессор", "aksessor"},
            {"акциз", "aksiz"},
            {"акция", "aksiya"},
            {"аннотация", "annotatsiya"},
            {"антифрикцион", "antifriksion"},
            {"апелляция", "apellyatsiya"},
            {"апробация", "aprobatsiya"},
            {"ассимиляция", "assimilyatsiya"},
            {"ассоциация", "assotsiatsiya"},
            {"аттестация", "attestatsiya"},
            {"аукцион", "auksion"},
            {"ацетон", "atseton"},
            {"ацтек", "atstek"},
            {"баренц", "barens"},
            {"вадуц", "vaduts"},
            {"вакцина", "vaksina"},
            {"вариация", "variatsiya"},
            {"вегетация", "vegetatsiya"},
            {"венеция", "venetsiya"},
            {"вентиляция", "ventilyatsiya"},
            {"вибрация", "vibratsiya"},
            {"вице-", "vitse-"},
            {"гелиоцентрик", "geliotsentrik"},
            {"геоцентрик", "geotsentrik"},
            {"герц", "gers"},
            {"герцог", "gersog"},
            {"гидратация", "gidratatsiya"},
            {"глобализация", "globalizatsiya"},
            {"горчица", "gorchitsa"},
            {"гравитацион", "gravitatsion"},
            {"гравитация", "gravitatsiya"},
            {"греция", "gretsiya"},
            {"даймлер-бенц", "daymler-bens"},
            {"данциг", "dansig"},
            {"девальвация", "devalvatsiya"},
            {"дегустация", "degustatsiya"},
            {"дедукция", "deduksiya"},
            {"дезактивация", "dezaktivatsiya"},
            {"декламация", "deklamatsiya"},
            {"декларация", "deklaratsiya"},
            {"декорация", "dekoratsiya"},
            {"делегация", "delegatsiya"},
            {"делимитация", "delimitatsiya"},
            {"демаркация", "demarkatsiya"},
            {"денонсация", "denonsatsiya"},
            {"депортация", "deportatsiya"},
            {"деривация", "derivatsiya"},
            {"детонация", "detonatsiya"},
            {"дефицит", "defitsit"},
            {"деформация", "deformatsiya"},
            {"децибел", "detsibel"},
            {"дециметр", "detsimetr"},
            {"диверсификация", "diversifikatsiya"},
            {"дирекция", "direksiya"},
            {"дисквалификация", "diskvalifikatsiya"},
            {"дискриминация", "diskriminatsiya"},
            {"дислокация", "dislokatsiya"},
            {"диссертация", "dissertatsiya"},
            {"диссимиляция", "dissimilyatsiya"},
            {"дифференциал", "differensial"},
            {"дифференциация", "differensiatsiya"},
            {"дифференция", "differensiya"},
            {"донецк", "donetsk"},
            {"дотация", "dotatsiya"},
            {"доцент", "dotsent"},
            {"жиу-жицу", "jiu-jitsu"},
            {"изоляция", "izolyatsiya"},
            {"иллюстрация", "illyustratsiya"},
            {"иммобилизация", "immobilizatsiya"},
            {"импровизация", "improvizatsiya"},
            {"инвестиция", "investitsiya"},
            {"индексация", "indeksatsiya"},
            {"индукция", "induksiya"},
            {"индульгенция", "indulgensiya"},
            {"инерция", "inersiya"},
            {"инквизиция", "inkvizitsiya"},
            {"инкубация", "inkubatsiya"},
            {"инспекция", "inspeksiya"},
            {"инструкция", "instruksiya"},
            {"инсценировка", "inssenirovka"},
            {"интеграция", "integratsiya"},
            {"интервенция", "intervensiya"},
            {"интерференция", "interferensiya"},
            {"интуиция", "intuitsiya"},
            {"инфекция", "infeksiya"},
            {"инфляция", "inflyatsiya"},
            {"информацион", "informatsion"},
            {"иррационал", "irratsional"},
            {"ирригация", "irrigatsiya"},
            {"кальций", "kalsiy"},
            {"канализация", "kanalizatsiya"},
            {"канцлер", "kansler"},
            {"капитуляция", "kapitulyatsiya"},
            {"кассация", "kassatsiya"},
            {"католицизм", "katolitsizm"},
            {"квалификация", "kvalifikatsiya"},
            {"кварц", "kvars"},
            {"классификация", "klassifikatsiya"},
            {"классицизм", "klassitsizm"},
            {"коллекция", "kolleksiya"},
            {"колонизация", "kolonizatsiya"},
            {"комбинация", "kombinatsiya"},
            {"коммерция", "kommersiya"},
            {"коммуникация", "kommunikatsiya"},
            {"компенсация", "kompensatsiya"},
            {"композиция", "kompozitsiya"},
            {"конвекция", "konveksiya"},
            {"конвенция", "konvensiya"},
            {"консервация", "konservatsiya"},
            {"консолидация", "konsolidatsiya"},
            {"консорциум", "konsorsium"},
            {"консорция", "konsorsiya"},
            {"констанца", "konstansa"},
            {"конституция", "konstitutsiya"},
            {"конструкция", "konstruksiya"},
            {"консультация", "konsultatsiya"},
            {"конфедерация", "konfederatsiya"},
            {"конференция", "konferensiya"},
            {"концентрат", "konsentrat"},
            {"концентрация", "konsentratsiya"},
            {"концепт", "konsept"},
            {"концепция", "konsepsiya"},
            {"концерн", "konsern"},
            {"концерт", "konsert"},
            {"концессия", "konsessiya"},
            {"концлагерь", "konslager"},
            {"конъюнкция", "kon’yunksiya"},
            {"координация", "koordinatsiya"},
            {"корпорация", "korporatsiya"},
            {"коррекция", "korreksiya"},
            {"корреспонденция", "korrespondensiya"},
            {"коррупция", "korrupsiya"},
            {"коэффициент", "koeffitsiyent"},
            {"культивация", "kultivatsiya"},
            {"лактация", "laktatsiya"},
            {"Лейпциг", "Leypsig"},
            {"лейцит", "leysit"},
            {"лекция", "leksiya"},
            {"лицей", "litsey"},
            {"лицензия", "litsenziya"},
            {"лиценциат", "litsensiat"},
            {"майнц", "mayns"},
            {"марганец", "marganets"},
            {"марганцовка", "margansovka"},
            {"матрица", "matritsa"},
            {"мелиорация", "melioratsiya"},
            {"менингококкцемия", "meningokokksemiya"},
            {"Мерседес-бенц", "Mersedes-bens"},
            {"механизация", "mexanizatsiya"},
            {"миграция", "migratsiya"},
            {"милиция", "militsiya"},
            {"модернизация", "modernizatsiya"},
            {"модификация", "modifikatsiya"},
            {"модуляция", "modulyatsiya"},
            {"мотоцикл", "motosikl"},
            {"муниципал", "munitsipal"},
            {"муниципалитет", "munitsipalitet"},
            {"мутация", "mutatsiya"},
            {"мцири", "mtsiri"},
            {"навигация", "navigatsiya"},
            {"национализация", "natsionalizatsiya"},
            {"национализм", "natsionalizm"},
            {"нацист", "natsist"},
            {"ницца", "nitssa"},
            {"облигация", "obligatsiya"},
            {"оккупация", "okkupatsiya"},
            {"оксигенация", "oksigenatsiya"},
            {"операция", "operatsiya"},
            {"осциллограф", "ossillograf"},
            {"офицер", "ofitser"},
            {"патриций", "patritsiy"},
            {"плантация", "plantatsiya"},
            {"плацдарм", "platsdarm"},
            {"плацента", "platsenta"},
            {"позиция", "pozitsiya"},
            {"полиция", "politsiya"},
            {"популяция", "populyatsiya"},
            {"потенциал", "potensial"},
            {"принцип", "prinsip"},
            {"провинция", "provinsiya"},
            {"проекция", "proyeksiya"},
            {"пропорционал", "proporsional"},
            {"пропорция", "proporsiya"},
            {"процесс", "protsess"},
            {"публицист", "publitsist"},
            {"публицистик", "publitsistik"},
            {"радиация", "radiatsiya"},
            {"радиолокация", "radiolokatsiya"},
            {"ратификация", "ratifikatsiya"},
            {"рацион", "ratsion"},
            {"рационал", "ratsional"},
            {"реабилитация", "reabilitatsiya"},
            {"реакция", "reaksiya"},
            {"реализация", "realizatsiya"},
            {"реанимация", "reanimatsiya"},
            {"революция", "revolyutsiya"},
            {"регуляция", "regulyatsiya"},
            {"редакция", "redaksiya"},
            {"редукция", "reduksiya"},
            {"резервация", "rezervatsiya"},
            {"рекреация", "rekreatsiya"},
            {"репродукция", "reproduksiya"},
            {"рецепт", "retsept"},
            {"рецептор", "retseptor"},
            {"рецидивист", "retsidivist"},
            {"рицар", "ritsar"},
            {"сан-франциско", "san-fransisko"},
            {"седиментация", "sedimentatsiya"},
            {"секреция", "sekretsiya"},
            {"секция", "seksiya"},
            {"селекция", "seleksiya"},
            {"сепарация", "separatsiya"},
            {"сигнализация", "signalizatsiya"},
            {"Сицилия", "Sitsiliya"},
            {"сланец", "slanets"},
            {"социализм", "sotsializm"},
            {"социология", "sotsiologiya"},
            {"станция", "stansiya"},
            {"стационар", "statsionar"},
            {"ступица", "stupitsa"},
            {"сукцинат", "suksinat"},
            {"сценарий", "ssenariy"},
            {"сянцзи", "syanszi"},
            {"тенденция", "tendensiya"},
            {"транскрипция", "transkripsiya"},
            {"транснационал", "transnatsional"},
            {"трансформация", "transformatsiya"},
            {"трапеция", "trapetsiya"},
            {"унция", "unsiya"},
            {"фармацевтика", "farmatsevtika"},
            {"федерация", "federatsiya"},
            {"Флоренция", "Florensiya"},
            {"формация", "formatsiya"},
            {"фракция", "fraksiya"},
            {"франций", "fransiy"},
            {"франциск", "fransisk"},
            {"Франция", "Fransiya"},
            {"француз", "fransuz"},
            {"фрикцион", "friksion"},
            {"функция", "funksiya"},
            {"халцедон", "xalsedon"},
            {"холецистит", "xoletsistit"},
            {"цезий", "seziy"},
            {"цейтнот", "seytnot"},
            {"целлофан", "sellofan"},
            {"целлюлоза", "sellyuloza"},
            {"цельсий", "selsiy"},
            {"цемент", "sement"},
            {"цензор", "senzor"},
            {"цензура", "senzura"},
            {"центнер", "sentner"},
            {"цех", "sex"},
            {"цеце", "setse"},
            {"цеце", "setse"},
            {"цивилизация", "sivilizatsiya"},
            {"цикл", "sikl"},
            {"циклон", "siklon"},
            {"циклоп", "siklop"},
            {"цилиндр", "silindr"},
            {"цилиндрик", "silindrik"},
            {"цилиндрсимон", "silindrsimon"},
            {"цирк", "sirk"},
            {"циркуль", "sirkul"},
            {"циркуляция", "sirkulyatsiya"},
            {"цистерна", "sisterna"},
            {"цитрус", "sitrus"},
            {"черепица", "cherepitsa"},
            {"Швейцария", "Shveysariya"},
            {"Швеция", "Shvetsiya"},
            {"шприц", "shprits"},
            {"эволюция", "evolyutsiya"},
            {"эквиваленция", "ekvivalensiya"},
            {"экспедиция", "ekspeditsiya"},
            {"эксплуатация", "ekspluatatsiya"},
            {"экспозиция", "ekspozitsiya"},
            {"экстракция", "ekstraksiya"},
            {"эксцентриситет", "ekssentrisitet"},
            {"электрострикция", "elektrostriksiya"},
            {"эмансипация", "emansipatsiya"},
            {"эмиграция", "emigratsiya"},
            {"эмоция", "emotsiya"},
            {"энциклопедик", "ensiklopedik"},
            {"энциклопедия", "ensiklopediya"},
            {"эпилейцит", "epileysit"},
            {"эпицентр", "epitsentr"},
            {"эссенция", "essensiya"},
            {"юрисдикция", "yurisdiksiya"},
            {"юриспруденция", "yurisprudensiya"},
            {"янцзи", "yanszi"},
            {"сентябр", "sentabr"},
            {"сентябр", "sentyabr"},
            {"октябрь", "oktabr"},
            {"октябрь", "oktyabr"},
            {"бюджет", "budjet"},
            {"меценат", "mesenat"},
            {"нуқтаи назар", "nuqtayi nazar"},
            {"биолюминесценция", "biolyuminessensiya"},
            {"дифференциация", "differensiatsiya"},
            {"галлюцинация", "gallyutsinatsiya"},
            {"телеинсценировка", "teleinssenirovka"},
            {"люминесценция", "lyuminessensiya"},
            {"рекогносцировка", "rekognossirovka"},
            {"цитодиагностика", "sitodiagnostika"},
            {"бронеавтомобиль", "broneavtomobil"},
            {"бронеавтомобил", "broneavtomobil"},
            {"диссоциация", "dissotsiatsiya"},
            {"нитроглицерин", "nitroglitserin"},
            {"штангенциркуль", "shtangensirkul"},
            {"штангенциркул", "shtangensirkul"},
            {"альма-терапия", "alma-terapiya"},
            {"автомагистраль", "avtomagistral"},
            {"автомагистрал", "avtomagistral"},
            {"гелиоцентрик", "geliotsentrik"},
            {"коэффициент", "koeffitsiyent"},
            {"полицмейстер", "politsmeyster"},
            {"предохранитель", "predoxranitel"},
            {"предохранител", "predoxranitel"},
            {"радиоспектакль", "radiospektakl"},
            {"радиоспектакл", "radiospektakl"},
            {"реэмиграция", "reemigratsiya"},
            {"реэвакуация", "reevakuatsiya"},
            {"цивилизация", "sivilizatsiya"},
            {"девальвация", "devalvatsiya"},
            {"инсценировка", "inssenirovka"},
            {"капельмейстер", "kapelmeyster"},
            {"кинофестиваль", "kinofestival"},
            {"кинофестивал", "kinofestival"},
            {"киносценарий", "kinossenariy"},
            {"левомицетин", "levomitsetin"},
            {"пульверизатор", "pulverizator"},
            {"ревальвация", "revalvatsiya"},
            {"сутэмизувчи", "sutemizuvchi"},
            {"виключатель", "viklyuchatel"},
            {"виключател", "viklyuchatel"},
            {"юрисконсульт", "yuriskonsult"},
            {"автоприцеп", "avtopritsep"},
            {"бактерицид", "bakteritsid"},
            {"бруцеллёз", "brutsellyoz"},
            {"фельдмаршал", "feldmarshal"},
            {"геоцентрик", "geotsentrik"},
            {"гляциолог", "glyatsiolog"},
            {"киноконцерт", "kinokonsert"},
            {"конферансье", "konferansye"},
            {"микроинсульт", "mikroinsult"},
            {"монокультура", "monokultura"},
            {"пенициллин", "penitsillin"},
            {"пресс-папье", "press-papye"},
            {"реципиент", "retsipiyent"},
            {"шмуцтитул", "shmutstitul"},
            {"включатель", "vklyuchatel"},
            {"включател", "vklyuchatel"},
            {"холецистит", "xoletsistit"},
            {"адъюнктура", "adyunktura"},
            {"адъюнкт", "adyunkt"},
            {"большевизм", "bolshevizm"},
            {"броненосец", "bronenoses"},
            {"черепица", "cherepitsa"},
            {"эскадрилья", "eskadrilya"},
            {"физкультура", "fizkultura"},
            {"фортепьяно", "fortepyano"},
            {"фотоателье", "fotoatelye"},
            {"гипосульфит", "giposulfit"},
            {"гипоцентр", "gipotsentr"},
            {"горизонталь", "gorizontal"},
            {"горизонтал", "gorizontal"},
            {"готовальний", "gotovalniy"},
            {"канцероген", "kanserogen"},
            {"кастрюлька", "kastryulka"},
            {"колонцифра", "kolonsifra"},
            {"концепция", "konsepsiya"},
            {"концессия", "konsessiya"},
            {"коррупция", "korrupsiya"},
            {"лицензия", "litsenziya"},
            {"марсельеза", "marselyeza"},
            {"меньшевизм", "menshevizm"},
            {"микрорайон", "mikrorayon"},
            {"мизансцена", "mizanssena"},
            {"муниципал", "munitsipal"},
            {"офтальмолог", "oftalmolog"},
            {"пальпация", "palpatsiya"},
            {"почтальон", "pochtalyon"},
            {"пульмонолог", "pulmonolog"},
            {"қайнэгачи", "qaynegachi"},
            {"рецензент", "retsenzent"},
            {"рецензия", "retsenziya"},
            {"целлюлоза", "sellyuloza"},
            {"центрифуга", "sentrifuga"},
            {"цитология", "sitologiya"},
            {"сцинтиграф", "ssintigraf"},
            {"тенденциоз", "tendensioz"},
            {"уборшица", "uborshitsa"},
            {"валерьянка", "valeryanka"},
            {"вальвация", "valvatsiya"},
            {"виолончель", "violonchel"},
            {"виолончел", "violonchel"},
            {"холодильник", "xolodilnik"},
            {"арьергард", "aryergard"},
            {"ацетилен", "atsetilen"},
            {"авианосец", "avianoses"},
            {"автомобиль", "avtomobil"},
            {"автомобил", "avtomobil"},
            {"биомицин", "biomitsin"},
            {"большевик", "bolshevik"},
            {"бюллетень", "byulleten"},
            {"бюллетен", "byulleten"},
            {"эпицентр", "epitsentr"},
            {"фельдъегерь", "feldyeger"},
            {"фельдъегер", "feldyeger"},
            {"фотоальбом", "fotoalbom"},
            {"геральдика", "geraldika"},
            {"гербицид", "gerbitsid"},
            {"глицерин", "glitserin"},
            {"горчица", "gorchitsa"},
            {"гусеница", "gusenitsa"},
            {"инъекция", "inyeksiya"},
            {"катапульта", "katapulta"},
            {"компаньон", "kompanyon"},
            {"компьютер", "kompyuter"},
            {"конференц", "konferens"},
            {"конфуций", "konfutsiy"},
            {"концлагерь", "konslager"},
            {"концлагер", "konslager"},
            {"культуризм", "kulturizm"},
            {"лютеций", "lyutetsiy"},
            {"магистраль", "magistral"},
            {"магистрал", "magistral"},
            {"медицина", "meditsina"},
            {"меньшевик", "menshevik"},
            {"микрофильм", "mikrofilm"},
            {"миноносец", "minonoses"},
            {"официант", "ofitsiant"},
            {"оккультизм", "okkultizm"},
            {"ординарец", "ordinares"},
            {"пацифист", "patsifist"},
            {"пацифизм", "patsifizm"},
            {"пациент", "patsiyent"},
            {"пестицид", "pestitsid"},
            {"плацдарм", "platsdarm"},
            {"плацкарт", "platskart"},
            {"плебисцит", "plebissit"},
            {"целлулоид", "selluloid"},
            {"циферблат", "siferblat"},
            {"циркуляр", "sirkulyar"},
            {"цитокимё", "sitokimyo"},
            {"социолог", "sotsiolog"},
            {"специфик", "spetsifik"},
            {"технеций", "texnetsiy"},
            {"ультиматум", "ultimatum"},
            {"умивальник", "umivalnik"},
            {"вермишель", "vermishel"},
            {"вермишел", "vermishel"},
            {"вестибюль", "vestibyul"},
            {"вестибюл", "vestibyul"},
            {"видеофильм", "videofilm"},
            {"акционер", "aksioner"},
            {"альбатрос", "albatros"},
            {"альпинист", "alpinist"},
            {"альпинизм", "alpinizm"},
            {"амальгама", "amalgama"},
            {"арьергард", "arergard"},
            {"бандероль", "banderol"},
            {"бандерол", "banderol"},
            {"барельеф", "barelyef"},
            {"батальон", "batalyon"},
            {"бацилла", "batsilla"},
            {"бельведер", "belveder"},
            {"биофильтр", "biofiltr"},
            {"браконьер", "brakoner"},
            {"будильник", "budilnik"},
            {"бульденеж", "buldenej"},
            {"бульдозер", "buldozer"},
            {"диагональ", "diagonal"},
            {"диагонал", "diagonal"},
            {"дирижабль", "dirijabl"},
            {"дирижабл", "dirijabl"},
            {"двигатель", "dvigatel"},
            {"двигател", "dvigatel"},
            {"эмульсия", "emulsiya"},
            {"эндшпиль", "endshpil"},
            {"эндшпил", "endshpil"},
            {"фагоцит", "fagotsit"},
            {"фальсифик", "falsifik"},
            {"фельдшер", "feldsher"},
            {"фестиваль", "festival"},
            {"фестивал", "festival"},
            {"фитонцид", "fitonsid"},
            {"гаубица", "gaubitsa"},
            {"геноцид", "genotsid"},
            {"гиацинт", "giatsint"},
            {"госпиталь", "gospital"},
            {"госпитал", "gospital"},
            {"интервью", "intervyu"},
            {"инвентарь", "inventar"},
            {"инвентар", "inventar"},
            {"календарь", "kalendar"},
            {"календар", "kalendar"},
            {"калькуля", "kalkulya"},
            {"кастрюль", "kastryul"},
            {"кастрюл", "kastryul"},
            {"кинофильм", "kinofilm"},
            {"концентр", "konsentr"},
            {"консульта", "konsulta"},
            {"конвейер", "konveyer"},
            {"марганец", "marganes"},
            {"матрица", "matritsa"},
            {"медальон", "medalyon"},
            {"модельер", "modelyer"},
            {"монастирь", "monastir"},
            {"монастир", "monastir"},
            {"нимпальто", "nimpalto"},
            {"параллель", "parallel"},
            {"параллел", "parallel"},
            {"павильон", "pavilyon"},
            {"печенье", "pechenye"},
            {"петлица", "petlitsa"},
            {"пойабзал", "poyabzal"},
            {"пойафзал", "poyafzal"},
            {"пойандоз", "poyandoz"},
            {"пойустун", "poyustun"},
            {"процент", "protsent"},
            {"процесс", "protsess"},
            {"рентабель", "rentabel"},
            {"рентабел", "rentabel"},
            {"рецидив", "retsidiv"},
            {"револьвер", "revolver"},
            {"рубильник", "rubilnik"},
            {"секретарь", "sekretar"},
            {"секретар", "sekretar"},
            {"сельдерей", "selderey"},
            {"целлофан", "sellofan"},
            {"сентябрь", "sentyabr"},
            {"сентябр", "sentyabr"},
            {"шифоньер", "shifoner"},
            {"шницель", "shnitsel"},
            {"шницел", "shnitsel"},
            {"шпиндель", "shpindel"},
            {"шпиндел", "shpindel"},
            {"штемпель", "shtempel"},
            {"штемпел", "shtempel"},
            {"штепсель", "shtepsel"},
            {"штепсел", "shtepsel"},
            {"швейцар", "shveysar"},
            {"силиций", "silitsiy"},
            {"цистерна", "sisterna"},
            {"спектакль", "spektakl"},
            {"спектакл", "spektakl"},
            {"сценарий", "ssenariy"},
            {"стронций", "stronsiy"},
            {"таблица", "tablitsa"},
            {"телефильм", "telefilm"},
            {"теплица", "teplitsa"},
            {"ведомость", "vedomost"},
            {"ведомост", "vedomost"},
            {"абсцесс", "abssess"},
            {"акварель", "akletel"},
            {"акварел", "akletel"},
            {"алкоголь", "alkogol"},
            {"алкогол", "alkogol"},
            {"ансамбль", "ansambl"},
            {"ансамбл", "ansambl"},
            {"апельсин", "apelsin"},
            {"ацетон", "atseton"},
            {"бельэтаж", "beletaj"},
            {"бельгия", "belgiya"},
            {"бельтинг", "belting"},
            {"бильярд", "bilyard"},
            {"болонья", "bolonya"},
            {"боцман", "botsman"},
            {"диафильм", "diafilm"},
            {"доцент", "dotsent"},
            {"энцефал", "ensefal"},
            {"эсминец", "esmines"},
            {"фельетон", "feleton"},
            {"фольклор", "folklor"},
            {"француз", "fransuz"},
            {"гастроль", "gastrol"},
            {"гастрол", "gastrol"},
            {"гельминт", "gelmint"},
            {"горельеф", "gorelef"},
            {"интерьер", "interer"},
            {"итальян", "italyan"},
            {"женьшень", "jenshen"},
            {"женьшен", "jenshen"},
            {"канифоль", "kanifol"},
            {"канифол", "kanifol"},
            {"канцлер", "kansler"},
            {"капсюль", "kapsyul"},
            {"капсюл", "kapsyul"},
            {"карамель", "karamel"},
            {"карамел", "karamel"},
            {"картечь", "kartech"},
            {"картеч", "kartech"},
            {"карусель", "karusel"},
            {"карусел", "karusel"},
            {"коктейль", "kokteyl"},
            {"коктейл", "kokteyl"},
            {"концерн", "konsern"},
            {"концерт", "konsert"},
            {"контроль", "kontrol"},
            {"контрол", "kontrol"},
            {"конъюнктура", "konyunktura"},
            {"коньюктивит", "konyuktivit"},
            {"кульмина", "kulmina"},
            {"культива", "kultiva"},
            {"лоцман", "lotsman"},
            {"майонез", "mayonez"},
            {"мельхиор", "melxior"},
            {"мольберт", "molbert"},
            {"офицер", "ofitser"},
            {"октябрь", "oktyabr"},
            {"октябр", "oktyabr"},
            {"партьер", "partyer"},
            {"пенальти", "penalti"},
            {"пластирь", "plastir"},
            {"пластир", "plastir"},
            {"поршень", "porshen"},
            {"поршен", "porshen"},
            {"портфель", "portfel"},
            {"портфел", "portfel"},
            {"премьер", "premyer"},
            {"пристань", "pristan"},
            {"пристан", "pristan"},
            {"прицеп", "pritsep"},
            {"разъезд", "razyezd"},
            {"рецепт", "retsept"},
            {"центнер", "sentner"},
            {"цензура", "senzura"},
            {"цесарка", "sesarka"},
            {"цейтнот", "seytnot"},
            {"шагрень", "shagren"},
            {"шагрен", "shagren"},
            {"шампунь", "shampun"},
            {"шампун", "shampun"},
            {"шпатель", "shpatel"},
            {"шпател", "shpatel"},
            {"шпилька", "shpilka"},
            {"штапель", "shtapel"},
            {"штапел", "shtapel"},
            {"цилиндр", "silindr"},
            {"цитолиз", "sitoliz"},
            {"скальпель", "skalpel"},
            {"скальпел", "skalpel"},
            {"стержень", "sterjen"},
            {"стержен", "sterjen"},
            {"субъект", "subyekt"},
            {"текстиль", "tekstil"},
            {"текстил", "tekstil"},
            {"вакцина", "vaksina"},
            {"варьете", "letyete"},
            {"верньер", "vernyer"},
            {"виньетка", "vinetka"},
            {"водевиль", "vodevil"},
            {"водевил", "vodevil"},
            {"вольфрам", "volfram"},
            {"хрусталь", "xrustal"},
            {"хрустал", "xrustal"},
            {"акцент", "aksent"},
            {"акция", "aksiya"},
            {"альянс", "alyans"},
            {"артикль", "artikl"},
            {"артикл", "artikl"},
            {"асфальт", "asfalt"},
            {"ателье", "atelye"},
            {"бальнео", "balneo"},
            {"бальзам", "balzam"},
            {"барьер", "baryer"},
            {"баррель", "barrel"},
            {"баррел", "barrel"},
            {"базальт", "bazalt"},
            {"бинокль", "binokl"},
            {"бинокл", "binokl"},
            {"бульдог", "buldog"},
            {"бульон", "bulyon"},
            {"бульвар", "bullet"},
            {"чизель", "chizel"},
            {"чизел", "chizel"},
            {"дальтон", "dalton"},
            {"декабрь", "dekabr"},
//            {"декабр", "dekabr"},
            {"дельфин", "delfin"},
            {"факульт", "fakult"},
            {"февраль", "fevral"},
            {"феврал", "fevral"},
            {"гальван", "galvan"},
            {"гантель", "gantel"},
            {"гантел", "gantel"},
            {"гармонь", "garmon"},
            {"гармон", "garmon"},
            {"герцог", "gersog"},
            {"грифель", "grifel"},
            {"грифел", "grifel"},
            {"импульс", "impuls"},
            {"инсульт", "insult"},
            {"кальций", "kalsiy"},
            {"каратэ", "karate"},
            {"карьер", "karyer"},
            {"картель", "kartel"},
            {"картел", "kartel"},
            {"кобальт", "kobalt"},
            {"коньяк", "konyak"},
            {"кровать", "krovat"},
            {"кроват", "krovat"},
            {"курьер", "kuryer"},
            {"ланцет", "lanset"},
            {"лицей", "litsey"},
            {"лосьон", "losyon"},
            {"мигрень", "migren"},
            {"мигрен", "migren"},
            {"мойупа", "moyupa"},
            {"ниппель", "nippel"},
            {"ниппел", "nippel"},
            {"ноябрь", "noyabr"},
            {"ноябр", "noyabr"},
            {"область", "oblast"},
            {"област", "oblast"},
            {"объект", "obyekt"},
            {"патруль", "patrul"},
            {"патрул", "patrul"},
            {"печать", "pechat"},
            {"печат", "pechat"},
            {"пинцет", "pinset"},
            {"пицца", "pitssa"},
            {"плейер", "pleyer"},
            {"повесть", "povest"},
            {"повест", "povest"},
            {"профиль", "profil"},
            {"профил", "profil"},
            {"пульпит", "pulpit"},
            {"рантье", "rantye"},
            {"рельеф", "relyef"},
            {"ретушь", "retush"},
            {"ретуш", "retush"},
            {"рицарь", "ritsar"},
            {"рицар", "ritsar"},
            {"цельсий", "selsiy"},
            {"цемент", "sement"},
            {"сеньор", "senyor"},
            {"цензор", "senzor"},
            {"шинель", "shinel"},
            {"шинел", "shinel"},
            {"шприц", "shpris"},
            {"циркуль", "sirkul"},
            {"циркул", "sirkul"},
            {"цирроз", "sirroz"},
            {"цистит", "sistit"},
            {"цитата", "sitata"},
            {"цитрус", "sitrus"},
            {"сланец", "slanes"},
            {"слесарь", "slesar"},
            {"слесар", "slesar"},
            {"спираль", "spiral"},
            {"спирал", "spiral"},
            {"статья", "statya"},
            {"стайер", "stayer"},
            {"стелька", "stelka"},
            {"сульфат", "sulfat"},
            {"цунами", "sunami"},
            {"съёмка", "syomka"},
            {"терцет", "terset"},
            {"тоннель", "tonnel"},
            {"тоннел", "tonnel"},
            {"туннель", "tunnel"},
            {"туннел", "tunnel"},
            {"тюлень", "tyulen"},
            {"тюлен", "tyulen"},
            {"вексель", "veksel"},
            {"вексел", "veksel"},
            {"вельвет", "velvet"},
            {"вентиль", "ventil"},
            {"вентил", "ventil"},
            {"вимпель", "vimpel"},
            {"вимпел", "vimpel"},
            {"волость", "volost"},
            {"волост", "volost"},
            {"вульгар", "vulgar"},
            {"январь", "yanvar"},
            {"январ", "yanvar"},
            {"йогурт", "yogurt"},
            {"абзац", "abzas"},
            {"акциз", "aksiz"},
            {"альбом", "albom"},
            {"апрель", "aprel"},
            {"апрел", "aprel"},
            {"артель", "artel"},
            {"артел", "artel"},
            {"дельта", "delta"},
            {"деталь", "detal"},
            {"детал", "detal"},
            {"дизель", "dizel"},
            {"дизел", "dizel"},
            {"фильтр", "filtr"},
            {"фольга", "folga"},
            {"фонарь", "fonar"},
            {"фонар", "fonar"},
            {"гавань", "gavan"},
            {"гаван", "gavan"},
            {"гильза", "gilza"},
            {"гуашь", "guash"},
            {"гуаш", "guash"},
            {"кабель", "kabel"},
            {"кабел", "kabel"},
            {"кафель", "kafel"},
            {"кафел", "kafel"},
            {"калька", "kalka"},
            {"кисель", "kisel"},
            {"кисел", "kisel"},
            {"китель", "kitel"},
            {"кител", "kitel"},
            {"князь", "knyaz"},
            {"княз", "knyaz"},
            {"коньки", "konki"},
            {"кремль", "kreml"},
            {"кремл", "kreml"},
            {"кварц", "klets"},
            {"лагерь", "lager"},
            {"лагер", "lager"},
            {"латунь", "latun"},
            {"латун", "latun"},
            {"лосось", "losos"},
            {"лосос", "losos"},
            {"майор", "mayor"},
            {"мебель", "mebel"},
            {"мебел", "mebel"},
            {"медаль", "medal"},
            {"медал", "medal"},
            {"модель", "model"},
            {"модел", "model"},
            {"мотель", "motel"},
            {"мотел", "motel"},
            {"мульти", "multi"},
            {"ненец", "nenes"},
            {"никель", "nikel"},
            {"никел", "nikel"},
            {"пальма", "palma"},
            {"пальто", "palto"},
            {"панель", "panel"},
            {"панел", "panel"},
            {"пароль", "parol"},
            {"парол", "parol"},
            {"педаль", "pedal"},
            {"педал", "pedal"},
            {"полька", "polka"},
            {"пульпа", "pulpa"},
            {"пьеса", "pyesa"},
            {"ранец", "ranes"},
            {"район", "rayon"},
            {"рэкет", "reket"},
            {"резьба", "rezba"},
            {"риель", "riyel"},
            {"риел", "riyel"},
            {"рояль", "royal"},
            {"роял", "royal"},
            {"сальдо", "saldo"},
            {"сальто", "salto"},
            {"цанга", "sanga"},
            {"цапфа", "sapfa"},
            {"цедра", "sedra"},
            {"церий", "seriy"},
            {"цезий", "seziy"},
            {"цинга", "singa"},
            {"синька", "sinka"},
            {"сирень", "siren"},
            {"сирен", "siren"},
            {"соболь", "sobol"},
            {"собол", "sobol"},
            {"цоколь", "sokol"},
            {"цокол", "sokol"},
            {"судья", "sudya"},
            {"съезд", "syezd"},
            {"табель", "tabel"},
            {"табел", "tabel"},
            {"тигель", "tigel"},
            {"тигел", "tigel"},
            {"токарь", "tokar"},
            {"токар", "tokar"},
            {"ультра", "ultra"},
            {"ваниль", "vanil"},
            {"ванил", "vanil"},
            {"якорь", "yakor"},
            {"якор", "yakor"},
            {"альфа", "alfa"},
            {"бронь", "bron"},
            {"брон", "bron"},
            {"дрель", "drel"},
            {"дрел", "drel"},
            {"дуэль", "duel"},
            {"дуэл", "duel"},
            {"эмаль", "emal"},
            {"эмал", "emal"},
            {"фильм", "film"},
            {"фойе", "foye"},
            {"фриц", "fris"},
            {"герц", "gers"},
            {"гольф", "golf"},
            {"июль", "iyul"},
            {"июл", "iyul"},
            {"июнь", "iyun"},
            {"июн", "iyun"},
            {"кьят", "kyat"},
            {"нефть", "neft"},
            {"нефт", "neft"},
            {"отель", "otel"},
            {"отел", "otel"},
            {"печь", "pech"},
            {"печ", "pech"},
            {"пульс", "puls"},
            {"пульт", "pult"},
            {"рельс", "rels"},
            {"рубль", "rubl"},
            {"рубл", "rubl"},
            {"сельдь", "seld"},
            {"сельд", "seld"},
            {"цент", "sent"},
            {"ценз", "senz"},
            {"циан", "sian"},
            {"цикл", "sikl"},
            {"цинк", "sink"},
            {"цирк", "sirk"},
            {"стиль", "stil"},
            {"стил", "stil"},
            {"тальк", "talk"},
            {"тюль", "tyul"},
            {"тюл", "tyul"},
            {"утиль", "util"},
            {"утил", "util"},
            {"вальс", "vals"},
            {"верфь", "verf"},
            {"верф", "verf"},
            {"вольт", "volt"},
            {"йога", "yoga"},
            {"юань", "yuan"},
            {"юан", "yuan"},
            {"альт", "alt"},
            {"миль", "mil"},
            {"мил", "mil"},
            {"ноль", "nol"},
            {"нол", "nol"},
            {"роль", "rol"},
            {"рол", "rol"},
            {"руль", "rul"},
            {"рул", "rul"},
            {"цех", "sex"},
            {"янада", "yana-da"},
            {"сирка", "sirka"},
            {"сингари", "singari"},
            {"принцип", "prinsip"},
            {"деци", "detsi"},
            {"цикл", "sikl"},
            {"вице", "vitse"},
            {"девальвация", "devalvatsiya"},
            {"вальвация", "valvatsiya"},
            {"пенсия", "pensiya"},
            {"версия", "versiya"},
            {"жинсият", "jinsiyat"},
            {"сирка", "sirka"},
            {"сингари", "singari"},
            {"принцип", "prinsp"},
            {"деци", "detsi"},
            {"цикл", "sikl"},
            {"вице", "Vitse"},
            {"девальвация", "devalvatsiya"},
            {"вальвация", "valvatsiya"},
            {"версия", "versiya"},
            {"жинсият", "jinsiyat"},
            {"ашъарийлар", "ash'ariylar"},
            {"ашъор", "ash'or"},
            {"аълам", "a'lam"},
            {"аъло", "a'lo"},
            {"аълоҳазрат", "a'lohazrat"},
            {"аълочи", "a'lochi"},
            {"аълочилик", "a'lochilik"},
            {"аъмо", "a'mo"},
            {"аъмол", "a'mol"},
            {"аъмолий", "a'moliy"},
            {"аъмолий-тадрижий", "a'moliy-tadrijiy"},
            {"аъроф", "a'rof"},
            {"аъён", "a'yon"},
            {"аъзам", "a'zam"},
            {"аъзамият", "a'zamiyat"},
            {"аъзамлик", "a'zamlik"},
            {"аъзо", "a'zo"},
            {"аъзолик", "a'zolik"},
            {"аъзойи бадан", "a'zoyi badan"},
            {"арши аъло", "arshi a'lo"},
            {"алайҳиллаъна", "alayhilla'na"},
            {"алъамон", "al'amon"},
            {"амримаъруф", "amrima'ruf"},
            {"аҳли маърифат", "ahli ma'rifat"},
            {"абъод", "ab'od"},
            {"адабий-маърифий", "adabiy-ma'rifiy"},
            {"анъана", "an'ana"},
            {"анъанавий", "an'anaviy"},
            {"анъанавийлашган", "an'anaviylashgan"},
            {"анъанавийлик", "an'anaviylik"},
            {"ахлоқий-таълимий", "axloqiy-ta'limiy"},
            {"асъаса-дабдаба", "as'asa-dabdaba"},
            {"асъҳоб", "as'hob"},
            {"бадфеъл", "badfe'l"},
            {"бадфеъллашмоқ", "badfe'llashmoq"},
            {"бадфеъллик", "badfe'llik"},
            {"бадфеълона", "badfe'lona"},
            {"бадтаъм", "badta'm"},
            {"бадтаъмлик", "badta'mlik"},
            {"байъат", "bay'at"},
            {"бетаъкид", "beta'kid"},
            {"бетаълим", "beta'lim"},
            {"бетаълимлик", "beta'limlik"},
            {"бетаъм", "beta'm"},
            {"бетаъмлик", "beta'mlik"},
            {"бетаъриф", "beta'rif"},
            {"бетаъсир", "beta'sir"},
            {"бетаъсирланмоқ", "beta'sirlanmoq"},
            {"бетаъсирлик", "beta'sirlik"},
            {"бир дафъа", "bir daf'a"},
            {"бир даъфалик", "bir da'falik"},
            {"бир маъноли", "bir ma'noli"},
            {"бир меъёрда", "bir me'yorda"},
            {"бир меъёрдаги", "bir me'yordagi"},
            {"бирмаънолилик", "birma'nolilik"},
            {"битфеъл", "bitfe'l"},
            {"бамаъни", "bama'ni"},
            {"бамаънилик", "bama'nilik"},
            {"банотуннаъш", "banotunna'sh"},
            {"баъд", "ba'd"},
            {"баъда", "ba'da"},
            {"баъдаз", "ba'daz"},
            {"баъзан", "ba'zan"},
            {"баъзан-баъзан", "ba'zan-ba'zan"},
            {"баъзи", "ba'zi"},
            {"баъзи-баъзида", "ba'zi-ba'zida"},
            {"баъзи бир", "ba'zi bir"},
            {"баъзида", "ba'zida"},
            {"беэътибор", "bee'tibor"},
            {"беэътиборлик", "bee'tiborlik"},
            {"беэътиқод", "bee'tiqod"},
            {"беэътиқодлик", "bee'tiqodlik"},
            {"беэътироз", "bee'tiroz"},
            {"диққат-эътибор", "diqqat-e'tibor"},
            {"дарвешфеъл", "darveshfe'l"},
            {"девонафеъл", "devonafe'l"},
            {"девонафеъллик", "devonafe'llik"},
            {"давра-маърака", "davra-ma'raka"},
            {"даъват", "da'vat"},
            {"даъватгоҳ", "da'vatgoh"},
            {"даъваткор", "da'vatkor"},
            {"даъватнома", "da'vatnoma"},
            {"даъватчи", "da'vatchi"},
            {"даъватчилик", "da'vatchilik"},
            {"даъво", "da'vo"},
            {"даъво-достон", "da'vo-doston"},
            {"даъводор", "da'vodor"},
            {"даъвогар", "da'vogar"},
            {"даъвогарлик", "da'vogarlik"},
            {"даъволашиш", "da'volashish"},
            {"даъволашмоқ", "da'volashmoq"},
            {"даъвонома", "da'vonoma"},
            {"даъвосиз", "da'vosiz"},
            {"даъвосиз-талошсиз", "da'vosiz-taloshsiz"},
            {"даъвосизлик", "da'vosizlik"},
            {"даъвохат", "da'voxat"},
            {"даъвочи", "da'vochi"},
            {"дафъатандан", "daf'atandan"},
            {"эъдод", "e'dod"},
            {"эъдодий", "e'dodiy"},
            {"эъдом", "e'dom"},
            {"эъжоз", "e'joz"},
            {"эълон", "e'lon"},
            {"эълоннома", "e'lonnoma"},
            {"эътибор", "e'tibor"},
            {"эътиборан", "e'tiboran"},
            {"эътиборли", "e'tiborli"},
            {"эътиборлилик", "e'tiborlilik"},
            {"эътиборсиз", "e'tiborsiz"},
            {"эътиборсизлик", "e'tiborsizlik"},
            {"эътидол", "e'tidol"},
            {"эътимод", "e'timod"},
            {"эътимодли", "e'timodli"},
            {"эътимодлилик", "e'timodlilik"},
            {"эътимоднома", "e'timodnoma"},
            {"эътимодсиз", "e'timodsiz"},
            {"эътимодсизлик", "e'timodsizlik"},
            {"эътинозли", "e'tinozli"},
            {"эътиқод", "e'tiqod"},
            {"эътиқодий", "e'tiqodiy"},
            {"эътиқодли", "e'tiqodli"},
            {"эътиқодсиз", "e'tiqodsiz"},
            {"эътиқодсизлик", "e'tiqodsizlik"},
            {"эътироф", "e'tirof"},
            {"эътироз", "e'tiroz"},
            {"эътирозланмоқ", "e'tirozlanmoq"},
            {"эътирознома", "e'tiroznoma"},
            {"эътирозсиз", "e'tirozsiz"},
            {"эъзоз", "e'zoz"},
            {"эъзоз-икром", "e'zoz-ikrom"},
            {"эъзозламоқ", "e'zozlamoq"},
            {"эъзозланиш", "e'zozlanish"},
            {"эъзозланмоқ", "e'zozlanmoq"},
            {"эъзозлаш", "e'zozlash"},
            {"эъзозли", "e'zozli"},
            {"фотомаълумот", "fotoma'lumot"},
            {"феъл", "fe'l"},
            {"феъл-атвор", "fe'l-atvor"},
            {"феъл-хулқ", "fe'l-xulq"},
            {"феъл-хўй", "fe'l-xo‘y"},
            {"феъл-хўйли", "fe'l-xo‘yli"},
            {"феълан", "fe'lan"},
            {"феълдор", "fe'ldor"},
            {"феълдорлик", "fe'ldorlik"},
            {"феълли", "fe'lli"},
            {"фалсафий-таълимий", "falsafiy-ta'limiy"},
            {"фиръавн", "fir'avn"},
            {"фасъҳ", "fas'h"},
            {"гули машъал", "guli mash'al"},
            {"гулжаъфар", "gulja'far"},
            {"гулраъно", "gulra'no"},
            {"гултаъб", "gulta'b"},
            {"ҳадя-инъом", "hadya-in'om"},
            {"ҳайъат", "hay'at"},
            {"ҳайъатшунос", "hay'atshunos"},
            {"ҳайъатшунослик", "hay'atshunoslik"},
            {"ҳурмат-эъзоз", "hurmat-e'zoz"},
            {"ҳурталъат", "hurtal'at"},
            {"ҳурталъатлик", "hurtal'atlik"},
            {"ҳусни таълил", "husni ta'lil"},
            {"ҳайит-маърака", "hayit-ma'raka"},
            {"иззат-эътибор", "izzat-e'tibor"},
            {"ишонч-эътиқод", "ishonch-e'tiqod"},
            {"иъжоз", "i'joz"},
            {"иқтисодий-маъмурий", "iqtisodiy-ma'muriy"},
            {"инъикос", "in'ikos"},
            {"инъом", "in'om"},
            {"инъом-эҳсон", "in'om-ehson"},
            {"инъомли", "in'omli"},
            {"инъомнома", "in'omnoma"},
            {"истак-раъй", "istak-ra'y"},
            {"истеъдод", "iste'dod"},
            {"истеъдодли", "iste'dodli"},
            {"истеъдодлилик", "iste'dodlilik"},
            {"истеъдодсиз", "iste'dodsiz"},
            {"истеъдодсизлик", "iste'dodsizlik"},
            {"истеъфо", "iste'fo"},
            {"истеъмол", "iste'mol"},
            {"истеъмолчи", "iste'molchi"},
            {"истеъмолчилик", "iste'molchilik"},
            {"исъҳақ", "is'haq"},
            {"исъҳаққуш", "is'haqqush"},
            {"итфеъл", "itfe'l"},
            {"итфеъллик", "itfe'llik"},
            {"илм-маърифат", "ilm-ma'rifat"},
            {"илми таълиф", "ilmi ta'lif"},
            {"жаъфарий", "ja'fariy"},
            {"жаъфарийлик", "ja'fariylik"},
            {"журъат", "jur'at"},
            {"журъатланиш", "jur'atlanish"},
            {"журъатланмоқ", "jur'atlanmoq"},
            {"журъатлантирмоқ", "jur'atlantirmoq"},
            {"журъатли", "jur'atli"},
            {"журъатлилик", "jur'atlilik"},
            {"журъатсиз", "jur'atsiz"},
            {"журъатсизлик", "jur'atsizlik"},
            {"жузъий", "juz'iy"},
            {"жузъийлик", "juz'iylik"},
            {"киносанъат", "kinosan'at"},
            {"кўп маъноли", "ko‘p ma'noli"},
            {"кўпмаънолилик", "ko‘pma'nolilik"},
            {"каъба", "ka'ba"},
            {"каъбапўш", "ka'bapo‘sh"},
            {"каъбатулло", "ka'batullo"},
            {"каъбатуллоҳ", "ka'batulloh"},
            {"камэътибор", "kame'tibor"},
            {"камистеъмол", "kamiste'mol"},
            {"каммаълум", "kamma'lum"},
            {"каммаъно", "kamma'no"},
            {"каммаънолик", "kamma'nolik"},
            {"малъун", "mal'un"},
            {"малъунлик", "mal'unlik"},
            {"луғавий-маъновий", "lug‘aviy-ma'noviy"},
            {"ламъа", "lam'a"},
            {"лавҳа-маълумот", "lavha-ma'lumot"},
            {"лаъл", "la'l"},
            {"лаъли", "la'li"},
            {"лаълибадахшон", "la'libadaxshon"},
            {"лаънат", "la'nat"},
            {"лаънати", "la'nati"},
            {"лаънатламоқ", "la'natlamoq"},
            {"лаънатланиш", "la'natlanish"},
            {"лаънатланмоқ", "la'natlanmoq"},
            {"лаънатлов", "la'natlov"},
            {"лаънатнома", "la'natnoma"},
            {"муътақид", "mu'taqid"},
            {"муътазила", "mu'tazila"},
            {"муътазилийлар", "mu'taziliylar"},
            {"меъда", "me'da"},
            {"меъдаости", "me'daosti"},
            {"меъмор", "me'mor"},
            {"меъморий", "me'moriy"},
            {"меъморлик", "me'morlik"},
            {"меъморчилик", "me'morchilik"},
            {"меърож", "me'roj"},
            {"меърожнома", "me'rojnoma"},
            {"меъёр", "me'yor"},
            {"меъёрий", "me'yoriy"},
            {"меъёрийлик", "me'yoriylik"},
            {"меъёрлаштириш", "me'yorlashtirish"},
            {"меъёрли", "me'yorli"},
            {"меъёрнома", "me'yornoma"},
            {"меъёрсиз", "me'yorsiz"},
            {"масъҳ", "mas'h"},
            {"масъуд", "mas'ud"},
            {"масъудлик", "mas'udlik"},
            {"масъудона", "mas'udona"},
            {"масъул", "mas'ul"},
            {"масъулият", "mas'uliyat"},
            {"масъулиятли", "mas'uliyatli"},
            {"масъулиятсиз", "mas'uliyatsiz"},
            {"масъулиятсизлик", "mas'uliyatsizlik"},
            {"масъуллик", "mas'ullik"},
            {"моҳталъат", "mohtal'at"},
            {"мустаъмал", "musta'mal"},
            {"мусъҳаф", "mus'haf"},
            {"мусъҳафнавис", "mus'hafnavis"},
            {"минбаъд", "minba'd"},
            {"машъал", "mash'al"},
            {"машъала", "mash'ala"},
            {"машъала", "mash'ala"},
            {"машъалдек", "mash'aldek"},
            {"машъалдор", "mash'aldor"},
            {"машъалистон", "mash'aliston"},
            {"машъаллик", "mash'allik"},
            {"машъалсимон", "mash'alsimon"},
            {"машъум", "mash'um"},
            {"машъумлик", "mash'umlik"},
            {"маъбад", "ma'bad"},
            {"маъбуд", "ma'bud"},
            {"маъдан", "ma'dan"},
            {"маъданли", "ma'danli"},
            {"маъдансоз", "ma'dansoz"},
            {"маъдансозлик", "ma'dansozlik"},
            {"маъдансув", "ma'dansuv"},
            {"маъдансувли", "ma'dansuvli"},
            {"маъданшунос", "ma'danshunos"},
            {"маъданшунослик", "ma'danshunoslik"},
            {"маъданчи", "ma'danchi"},
            {"маъҳад", "ma'had"},
            {"маъжун", "ma'jun"},
            {"маълул", "ma'lul"},
            {"маълум", "ma'lum"},
            {"маълумингиз", "ma'lumingiz"},
            {"маълумки", "ma'lumki"},
            {"маълумлик", "ma'lumlik"},
            {"маълумот", "ma'lumot"},
            {"маълумот-ахборот", "ma'lumot-axborot"},
            {"маълумотбозлик", "ma'lumotbozlik"},
            {"маълумотфурушлик", "ma'lumotfurushlik"},
            {"маълумотли", "ma'lumotli"},
            {"маълумотлилик", "ma'lumotlilik"},
            {"маълумотнома", "ma'lumotnoma"},
            {"маълумотсиз", "ma'lumotsiz"},
            {"маълумотсизлик", "ma'lumotsizlik"},
            {"маъман", "ma'man"},
            {"маъмур", "ma'mur"},
            {"маъмура", "ma'mura"},
            {"маъмурий", "ma'muriy"},
            {"маъмурий-бюрократик", "ma'muriy-byurokratik"},
            {"маъмурий-ҳудудий", "ma'muriy-hududiy"},
            {"маъмурий-ҳуқуқий", "ma'muriy-huquqiy"},
            {"маъмурият", "ma'muriyat"},
            {"маъмуриятчи", "ma'muriyatchi"},
            {"маъмуриятчилик", "ma'muriyatchilik"},
            {"маъмурлик", "ma'murlik"},
            {"маъмурчилик", "ma'murchilik"},
            {"маънан", "ma'nan"},
            {"маънавий", "ma'naviy"},
            {"маънавий-ахлоқий", "ma'naviy-axloqiy"},
            {"маънавий-диний", "ma'naviy-diniy"},
            {"маънавий-ижтимоий", "ma'naviy-ijtimoiy"},
            {"маънавий-руҳий", "ma'naviy-ruhiy"},
            {"маънавий-сиёсий", "ma'naviy-siyosiy"},
            {"маънавият", "ma'naviyat"},
            {"маъни ва маъно", "ma'ni va ma'no"},
            {"маънили ва маъноли", "ma'nili va ma'noli"},
            {"маънисиз ва маъносиз", "ma'nisiz va ma'nosiz"},
            {"маъно", "ma'no"},
            {"маъно-мазмун", "ma'no-mazmun"},
            {"маъно-моҳият", "ma'no-mohiyat"},
            {"маъно ва маъни", "ma'no va ma’ni"},
            {"маънодор", "ma'nodor"},
            {"маънодорлик", "ma'nodorlik"},
            {"маънодош", "ma'nodosh"},
            {"маънодошлик", "ma'nodoshlik"},
            {"маъноли", "ma'noli"},
            {"маънолилик", "ma'nolilik"},
            {"маъносиз", "ma'nosiz"},
            {"маъносизлик", "ma'nosizlik"},
            {"маъновий", "ma'noviy"},
            {"маъновийлик", "ma'noviylik"},
            {"маъод", "ma'od"},
            {"маъқул", "ma'qul"},
            {"маъқулламоқ", "ma'qullamoq"},
            {"маъқулланиш", "ma'qullanish"},
            {"маъқулланмоқ", "ma'qullanmoq"},
            {"маъқуллатиш", "ma'qullatish"},
            {"маъқуллатмоқ", "ma'qullatmoq"},
            {"маъқуллаш", "ma'qullash"},
            {"маъқуллашмоқ", "ma'qullashmoq"},
            {"маъқуллик", "ma'qullik"},
            {"маъқуллов", "ma'qullov"},
            {"маъқулловчи", "ma'qullovchi"},
            {"маърака", "ma'raka"},
            {"маърака-майдон", "ma'raka-maydon"},
            {"маъракагир", "ma'rakagir"},
            {"маърамоқ", "ma'ramoq"},
            {"маъратмоқ", "ma'ratmoq"},
            {"маъраш", "ma'rash"},
            {"маърашмоқ", "ma'rashmoq"},
            {"маърифат", "ma'rifat"},
            {"маърифатланмоқ", "ma'rifatlanmoq"},
            {"маърифатлантириш", "ma'rifatlantirish"},
            {"маърифатлантирмоқ", "ma'rifatlantirmoq"},
            {"маърифатли", "ma'rifatli"},
            {"маърифатпарвар", "ma'rifatparvar"},
            {"маърифатпарварлик", "ma'rifatparvarlik"},
            {"маърифатпарварлик", "ma'rifatparvarlik"},
            {"маърифатсиз", "ma'rifatsiz"},
            {"маърифатсизлик", "ma'rifatsizlik"},
            {"маърифатчи", "ma'rifatchi"},
            {"маърифатчилик", "ma'rifatchilik"},
            {"маърифий", "ma'rifiy"},
            {"маърифий-ирфоний", "ma'rifiy-irfoniy"},
            {"маъруф", "ma'ruf"},
            {"маъруза", "ma'ruza"},
            {"маърузачи", "ma'ruzachi"},
            {"маъсум", "ma'sum"},
            {"маъсума", "ma'suma"},
            {"маъсумалик", "ma'sumalik"},
            {"маъсумият", "ma'sumiyat"},
            {"маъсумлик", "ma'sumlik"},
            {"маъсумона", "ma'sumona"},
            {"маъталь ва маҳтал", "ma'tal va mahtal"},
            {"маъво", "ma'vo"},
            {"маъюб", "ma'yub"},
            {"маъюс", "ma'yus"},
            {"маъюс-паришон", "ma'yus-parishon"},
            {"маъюсият", "ma'yusiyat"},
            {"маъюсланиш", "ma'yuslanish"},
            {"маъюсланмоқ", "ma'yuslanmoq"},
            {"маъюслантириш", "ma'yuslantirish"},
            {"маъюслантирмоқ", "ma'yuslantirmoq"},
            {"маъюслик", "ma'yuslik"},
            {"маъюсона", "ma'yusona"},
            {"маъзират", "ma'zirat"},
            {"маъзул", "ma'zul"},
            {"маъзун", "ma'zun"},
            {"маъзур", "ma'zur"},
            {"маъшуқ", "ma'shuq"},
            {"маъшуқа", "ma'shuqa"},
            {"маъшуқалик", "ma'shuqalik"},
            {"маъшуқлик", "ma'shuqlik"},
            {"маъшуқона", "ma'shuqona"},
            {"маданий-маърифий", "madaniy-ma'rifiy"},
            {"навбатчи-маъмур", "navbatchi-ma'mur"},
            {"ноанъанавий", "noan'anaviy"},
            {"нашъа", "nash'a"},
            {"нашъадор", "nash'ador"},
            {"нашъали", "nash'ali"},
            {"нашъасиз", "nash'asiz"},
            {"нашъасизлик", "nash'asizlik"},
            {"нашъу намо", "nash'u namo"},
            {"наъл", "na'l"},
            {"наългар", "na'lgar"},
            {"наълламоқ", "na'llamoq"},
            {"наъллатмоқ", "na'llatmoq"},
            {"наълли", "na'lli"},
            {"наълсиз", "na'lsiz"},
            {"наълчи", "na'lchi"},
            {"наълчилик", "na'lchilik"},
            {"наъматак", "na'matak"},
            {"наъра", "na'ra"},
            {"наърадор", "na'rador"},
            {"наът", "na't"},
            {"номасъул", "nomas'ul"},
            {"номаълум", "noma'lum"},
            {"номаълумлик", "noma'lumlik"},
            {"номаъқул", "noma'qul"},
            {"номаъқуллик", "noma'qullik"},
            {"номаъқулчилик", "noma'qulchilik"},
            {"неъмат", "ne'mat"},
            {"неъматли", "ne'matli"},
            {"номеъёрий", "nome'yoriy"},
            {"номеъёрлик", "nome'yorlik"},
            {"настаълиқ", "nasta'liq"},
            {"ноз-неъмат", "noz-ne'mat"},
            {"ноз-неъматли", "noz-ne'matli"},
            {"нозиктаъб", "nozikta'b"},
            {"ношаръий", "noshar'iy"},
            {"обрў-эътиборли", "obro‘-e'tiborli"},
            {"ошиқ-маъшуқ", "oshiq-ma'shuq"},
            {"ошиқ-маъшуқлик", "oshiq-ma'shuqlik"},
            {"пурмаъно", "purma'no"},
            {"пурнеъмат", "purne'mat"},
            {"қўнғирнаъматак", "qo‘ng‘irna'matak"},
            {"қалъа", "qal'a"},
            {"қалъабанди", "qal'abandi"},
            {"қалъадор", "qal'ador"},
            {"қалъадорлик", "qal'adorlik"},
            {"қалъачи", "qal'achi"},
            {"қаъда", "qa'da"},
            {"қаър", "qa'r"},
            {"қитъа", "qit'a"},
            {"қитъалараро", "qit'alararo"},
            {"қатъан", "qat'an"},
            {"қатъи назар", "qat'i nazar"},
            {"қатъий", "qat'iy"},
            {"қатъиян", "qat'iyan"},
            {"қатъият", "qat'iyat"},
            {"қатъияткор", "qat'iyatkor"},
            {"қатъияткорлик", "qat'iyatkorlik"},
            {"қатъиятли", "qat'iyatli"},
            {"қатъиятлилик", "qat'iyatlilik"},
            {"қатъиятсиз", "qat'iyatsiz"},
            {"қатъиятсизлик", "qat'iyatsizlik"},
            {"қатъийлашиш", "qat'iylashish"},
            {"қатъийлашмоқ", "qat'iylashmoq"},
            {"қатъийлаштириш", "qat'iylashtirish"},
            {"қатъийлаштирмоқ", "qat'iylashtirmoq"},
            {"қатъийлик", "qat'iylik"},
            {"қуръа", "qur'a"},
            {"қуръаандоз", "qur'aandoz"},
            {"қуръон", "qur'on"},
            {"қуръонхон", "qur'onxon"},
            {"рубъи маскун", "rub'i maskun"},
            {"руҳий-маънавий", "ruhiy-ma'naviy"},
            {"руқъа", "ruq'a"},
            {"радиомаъруза", "radioma'ruza"},
            {"раъд", "ra'd"},
            {"раъно", "ra'no"},
            {"раънодошлар", "ra'nodoshlar"},
            {"раъногулдошлар", "ra'noguldoshlar"},
            {"раъноли", "ra'noli"},
            {"раъвакўт", "ra'vako‘t"},
            {"раъй", "ra'y"},
            {"раъя", "ra'ya"},
            {"раъйихуш", "ra'yixush"},
            {"раъйиш", "ra'yish"},
            {"раъйишли", "ra'yishli"},
            {"раъйишсиз", "ra'yishsiz"},
            {"раъйишсизлик", "ra'yishsizlik"},
            {"суръат", "sur'at"},
            {"суръатли", "sur'atli"},
            {"серистеъмол", "seriste'mol"},
            {"сермаъно", "serma'no"},
            {"сермаънолик", "serma'nolik"},
            {"санъат", "san'at"},
            {"санъаткор", "san'atkor"},
            {"санъаткорлик", "san'atkorlik"},
            {"санъаткорона", "san'atkorona"},
            {"санъатпардоз", "san'atpardoz"},
            {"санъатпардозлик", "san'atpardozlik"},
            {"санъатшунос", "san'atshunos"},
            {"санъатшунослик", "san'atshunoslik"},
            {"санъатчи", "san'atchi"},
            {"санъатчилик", "san'atchilik"},
            {"саъва", "sa'va"},
            {"саъй", "sa'y"},
            {"саъй-ҳаракат", "sa'y-harakat"},
            {"сиёсий-маъмурий", "siyosiy-ma'muriy"},
            {"суиистеъмолчи", "suiiste'molchi"},
            {"суиистеъмолчилик", "suiiste'molchilik"},
            {"сунъий", "sun'iy"},
            {"сунъийлаштириш", "sun'iylashtirish"},
            {"сунъийлаштирмоқ", "sun'iylashtirmoq"},
            {"сунъийлик", "sun'iylik"},
            {"сир-аъмол", "sir-a'mol"},
            {"сертаъзим", "serta'zim"},
            {"соҳибистеъдод", "sohibiste'dod"},
            {"серваъда", "serva'da"},
            {"садри аъзам", "sadri a'zam"},
            {"саж'", "saj'"},
            {"тўй-маърака", "to‘y-ma'raka"},
            {"таржиъбанд", "tarji'band"},
            {"тасаввуфий-таълимий", "tasavvufiy-ta'limiy"},
            {"услубий-маъновий", "uslubiy-ma'noviy"},
            {"узр-маъзур", "uzr-ma'zur"},
            {"умумтаълим", "umumta'lim"},
            {"вусъат", "vus'at"},
            {"вазири аъзам", "vaziri a'zam"},
            {"ваъда", "va'da"},
            {"ваъдабоз", "va'daboz"},
            {"ваъдабозлик", "va'dabozlik"},
            {"ваъдабузар", "va'dabuzar"},
            {"ваъдагоҳ", "va'dagoh"},
            {"ваъдалашиш", "va'dalashish"},
            {"ваъдалашмоқ", "va'dalashmoq"},
            {"ваъдалашув", "va'dalashuv"},
            {"ваъдасиз", "va'dasiz"},
            {"ваъдасизлик", "va'dasizlik"},
            {"ваъдахилоф", "va'daxilof"},
            {"ваъдахилофлик", "va'daxiloflik"},
            {"ваъз", "va'z"},
            {"ваъз-насиҳат", "va'z-nasihat"},
            {"ваъзбоз", "va'zboz"},
            {"ваъзбозлик", "va'zbozlik"},
            {"ваъзгўй", "va'zgo‘y"},
            {"ваъзгўйлик", "va'zgo‘ylik"},
            {"ваъзхон", "va'zxon"},
            {"ваъзхонлик", "va'zxonlik"},
            {"ваъзчи", "va'zchi"},
            {"ваъзчилик", "va'zchilik"},
            {"валинеъмат", "valine'mat"},
            {"валлоҳиаълам", "vallohia'lam"},
            {"вара'", "vara'"},
            {"хушфеъл", "xushfe'l"},
            {"хушфеъллик", "xushfe'llik"},
            {"хуштаъб", "xushta'b"},
            {"хуштаъблик", "xushta'blik"},
            {"хуштаъм", "xushta'm"},
            {"хуштаъмлик", "xushta'mlik"},
            {"хатми қуръон", "xatmi qur'on"},
            {"хайр-маъзур", "xayr-ma'zur"},
            {"хилъат", "xil'at"},
            {"яъжуж-маъжуж", "ya'juj-ma'juj"},
            {"яъни", "ya'ni"},
            {"яъники", "ya'niki"},
            {"зулқаъда", "zulqa'da"},
            {"заъф", "za'f"},
            {"заъфар", "za'far"},
            {"заъфарон", "za'faron"},
            {"заъфаронлик", "za'faronlik"},
            {"зеҳн-истеъдод", "zehn-iste'dod"},
            {"шоиртаъб", "shoirta'b"},
            {"ғайришаръий", "g‘ayrishar'iy"},
            {"шуъба", "shu'ba"},
            {"шуъла", "shu'la"},
            {"шуъладор", "shu'lador"},
            {"шуълаланиш", "shu'lalanish"},
            {"шуълаланмоқ", "shu'lalanmoq"},
            {"шуълали", "shu'lali"},
            {"шуълақанотлилар", "shu'laqanotlilar"},
            {"шаръан", "shar'an"},
            {"шаъбон", "sha'bon"},
            {"шаън", "sha'n"},
            {"шаън-шавкат", "sha'n-shavkat"},
            {"шеъмамо", "she'mamo"},
            {"шеър", "she'r"},
            {"шеърбозлик", "she'rbozlik"},
            {"шеърдўстлик", "she'rdo‘stlik"},
            {"шеърфуруш", "she'rfurush"},
            {"шеърий", "she'riy"},
            {"шеърий-насрий", "she'riy-nasriy"},
            {"шеърият", "she'riyat"},
            {"шеърпараст", "she'rparast"},
            {"шеърсимон", "she'rsimon"},
            {"шеърхон", "she'rxon"},
            {"шеърхонлик", "she'rxonlik"},
            {"шеършунос", "she'rshunos"},
            {"шеършунослик", "she'rshunoslik"},
            {"шофиъийлар", "shofi'iylar"},
            {"шофиъийлик", "shofi'iylik"},
            {"шарий-маънавий", "shariy-ma'naviy"},
            {"бидъат", "bid'at"},
            {"бидъаткор", "bid'atkor"},
            {"бидъаткорлик", "bid'atkorlik"},
            {"бидъатчи", "bid'atchi"},
            {"бидъатчилик", "bid'atchilik"},
            {"билфеъл", "bilfe'l"},
            {"билим-маърифат", "bilim-ma'rifat"},
            {"билъакс", "bil'aks"},
            {"буқъа", "buq'a"},
            {"бемаъни", "bema'ni"},
            {"бемаъни-бебурд", "bema'ni-beburd"},
            {"бемаъни-беҳуда", "bema'ni-behuda"},
            {"бемаънидан бемаъни", "bema'nidan bema'ni"},
            {"бемаънигарчилик", "bema'nigarchilik"},
            {"бемаънилик ва бемаънолик", "bema'nilik va bema’nolik"},
            {"бемаъничилик", "bema'nichilik"},
            {"бемаъно", "bema'no"},
            {"бемаъно ва бемаъни", "bema'no va bema’ni"},
            {"бемаънолик ва бемаънилик", "bema'nolik va bema’nilik"},
            {"бемаърифат", "bema'rifat"},
            {"бемеъёр", "beme'yor"},
            {"таъамкорона", "ta'amkorona"},
            {"таъб", "ta'b"},
            {"таъбдор", "ta'bdor"},
            {"таъбир", "ta'bir"},
            {"таъбирича", "ta'biricha"},
            {"таъбирламоқ", "ta'birlamoq"},
            {"таъбирланмоқ", "ta'birlanmoq"},
            {"таъбирлашмоқ", "ta'birlashmoq"},
            {"таъбирли", "ta'birli"},
            {"таъбирнома", "ta'birnoma"},
            {"таъдиб", "ta'dib"},
            {"таъжил", "ta'jil"},
            {"таъкид", "ta'kid"},
            {"таъкидланмоқ", "ta'kidlanmoq"},
            {"таъкидлаш", "ta'kidlash"},
            {"таълиф", "ta'lif"},
            {"таълим", "ta'lim"},
            {"таълим-тарбия", "ta'lim-tarbiya"},
            {"таълимгоҳ", "ta'limgoh"},
            {"таълимий", "ta'limiy"},
            {"таълимли", "ta'limli"},
            {"таълимомуз", "ta'limomuz"},
            {"таълимот", "ta'limot"},
            {"таълимотли", "ta'limotli"},
            {"таълимотсиз", "ta'limotsiz"},
            {"таълимотчи", "ta'limotchi"},
            {"таълимсиз", "ta'limsiz"},
            {"таълиқ", "ta'liq"},
            {"таъм", "ta'm"},
            {"таъмин", "ta'min"},
            {"таъминлагич", "ta'minlagich"},
            {"таъминламоқ", "ta'minlamoq"},
            {"таъминланиш", "ta'minlanish"},
            {"таъминланмоқ", "ta'minlanmoq"},
            {"таъминлаш", "ta'minlash"},
            {"таъминлаштириш", "ta'minlashtirish"},
            {"таъминлов", "ta'minlov"},
            {"таъминловчи", "ta'minlovchi"},
            {"таъминотсизлик", "ta'minotsizlik"},
            {"таъминотчи", "ta'minotchi"},
            {"таъминотчилик", "ta'minotchilik"},
            {"таъмир", "ta'mir"},
            {"таъмирламоқ", "ta'mirlamoq"},
            {"таъмирлаш", "ta'mirlash"},
            {"таъмирот", "ta'mirot"},
            {"таъмирталаб", "ta'mirtalab"},
            {"таъмирчи", "ta'mirchi"},
            {"таъмирчилик", "ta'mirchilik"},
            {"таъмли", "ta'mli"},
            {"таъмлилик", "ta'mlilik"},
            {"таъмсиз", "ta'msiz"},
            {"таъмсизлик", "ta'msizlik"},
            {"таъна-дашном", "ta'na-dashnom"},
            {"таъна-маломат", "ta'na-malomat"},
            {"таъна-таадди", "ta'na-taaddi"},
            {"таъна-тазарру", "ta'na-tazarru"},
            {"таънадор", "ta'nador"},
            {"таънали", "ta'nali"},
            {"таънаомуз", "ta'naomuz"},
            {"таъначи", "ta'nachi"},
            {"таъначилик", "ta'nachilik"},
            {"таъқиб", "ta'qib"},
            {"таъқиб-тергов", "ta'qib-tergov"},
            {"таъқибламоқ", "ta'qiblamoq"},
            {"таъқибланиш", "ta'qiblanish"},
            {"таъқибланмоқ", "ta'qiblanmoq"},
            {"таъқибчи", "ta'qibchi"},
            {"таъқибчилик", "ta'qibchilik"},
            {"таъриф", "ta'rif"},
            {"таъриф-тавсиф", "ta'rif-tavsif"},
            {"таъриф-тавсия", "ta'rif-tavsiya"},
            {"таърифий", "ta'rifiy"},
            {"таърифича", "ta'rificha"},
            {"таърифламоқ", "ta'riflamoq"},
            {"таърифлаш", "ta'riflash"},
            {"таърифлашмоқ", "ta'riflashmoq"},
            {"таърифли", "ta'rifli"},
            {"таърифлов", "ta'riflov"},
            {"таърифловчи", "ta'riflovchi"},
            {"таърифнома", "ta'rifnoma"},
            {"таърифот", "ta'rifot"},
            {"таърих", "ta'rix"},
            {"таъриз", "ta'riz"},
            {"таъсип", "ta'sip"},
            {"таъсир", "ta'sir"},
            {"таъсирий", "ta'siriy"},
            {"таъсирламоқ", "ta'sirlamoq"},
            {"таъсирланиш", "ta'sirlanish"},
            {"таъсирланмоқ", "ta'sirlanmoq"},
            {"таъсирлантириш", "ta'sirlantirish"},
            {"таъсирлантирмоқ", "ta'sirlantirmoq"},
            {"таъсирлантирув", "ta'sirlantiruv"},
            {"таъсирлаш", "ta'sirlash"},
            {"таъсирли", "ta'sirli"},
            {"таъсирот", "ta'sirot"},
            {"таъсирсиз", "ta'sirsiz"},
            {"таъсирчан", "ta'sirchan"},
            {"таъсирчанлик", "ta'sirchanlik"},
            {"таъсис", "ta'sis"},
            {"таъсисчи", "ta'sischi"},
            {"таътил", "ta'til"},
            {"таътилланмоқ", "ta'tillanmoq"},
            {"таъвил", "ta'vil"},
            {"таъвия", "ta'viya"},
            {"таъвия-тараққос", "ta'viya-taraqqos"},
            {"таъвиз", "ta'viz"},
            {"таъзим", "ta'zim"},
            {"таъзим-тавозе", "ta'zim-tavoze"},
            {"таъзиман", "ta'ziman"},
            {"таъзимкор", "ta'zimkor"},
            {"таъзимламоқ", "ta'zimlamoq"},
            {"таъзимсиз", "ta'zimsiz"},
            {"таъзир", "ta'zir"},
            {"тальъат", "tal'at"},
            {"таъзия", "ta'ziya"},
            {"таъзиядор", "ta'ziyador"},
            {"таъзияли", "ta'ziyali"},
            {"таъзиянома", "ta'ziyanoma"},
            {"таъзияхона", "ta'ziyaxona"},
            {"таъзиячи", "ta'ziyachi"},
            {"таъзиячилик", "ta'ziyachilik"}
    };

    static {

        List<String[]> wordsList = new ArrayList<>();
        for (String[] word : WordsLibrary.wordsInitial) {
            if (!word[0].equals(word[0].toLowerCase()) && word[1].equals(word[1].toLowerCase())) {
                String[] wordTemp = new String[2];
                wordTemp[0] = word[0].toLowerCase();
                wordTemp[1] = word[1].toLowerCase();
                wordsList.add(wordTemp);
            }
        }
        int wordsInitialLength = WordsLibrary.wordsInitial.length;
        int len = wordsInitialLength + wordsList.size();
        WordsLibrary.words = new String[len][2];

        System.arraycopy(WordsLibrary.wordsInitial, 0, WordsLibrary.words, 0, wordsInitialLength);

        for (String[] word : wordsList) {
            WordsLibrary.words[wordsInitialLength++] = word;
        }

        var cyrillicLatinWords = new HashMap<Integer, List<String>>();
        var latinCyrillicWords = new HashMap<Integer, List<String>>();
        for (String[] word : WordsLibrary.words) {
            int hash0 = word[0].hashCode();
            int hash1 = word[1].hashCode();
            cyrillicLatinWords.computeIfAbsent(hash0, k -> new ArrayList<>());
            latinCyrillicWords.computeIfAbsent(hash1, k -> new ArrayList<>());
            cyrillicLatinWords.get(hash0).add(word[1]);
            latinCyrillicWords.get(hash1).add(word[0]);
        }

        cyrillicLatinWords.forEach((key, value) -> value.sort(Comparator.comparing(String::length).reversed()));
        latinCyrillicWords.forEach((key, value) -> value.sort(Comparator.comparing(String::length).reversed()));
        WordsLibrary.cyrillicLatinWords.putAll(Map.copyOf(cyrillicLatinWords));
        WordsLibrary.latinCyrillicWords.putAll(Map.copyOf(latinCyrillicWords));
    }

    private enum LETTER_CASES {
        CAMEL_CASE,
        UPPER_CASE,
        LOWER_CASE
    }
}


